# Generated by Django 5.2.6 on 2025-11-17 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Cost center for this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='core.costcenter'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='erp_production_order_number',
            field=models.CharField(blank=True, help_text='ERP Production Order Number', max_length=50),
        ),
    ]
