# Generated by Django 5.2.6 on 2025-11-18 22:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_cutterownershipcategory_and_more"),
        ("production", "0002_jobcard_cost_center_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "quotation_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique quotation number (auto-generated)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "quotation_date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Date quotation was created",
                    ),
                ),
                (
                    "valid_until_date",
                    models.DateField(
                        blank=True,
                        help_text="Quotation validity expiration date",
                        null=True,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer name (from job card)",
                        max_length=200,
                    ),
                ),
                (
                    "customer_order_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Customer's order reference",
                        max_length=200,
                    ),
                ),
                (
                    "total_cutter_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Total cost of cutters",
                        max_digits=14,
                    ),
                ),
                (
                    "total_labor_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Total labor cost",
                        max_digits=14,
                    ),
                ),
                (
                    "total_material_cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Total material/consumable cost",
                        max_digits=14,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Cutters + Labor + Materials",
                        max_digits=14,
                    ),
                ),
                (
                    "overhead_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("15.00"),
                        help_text="Overhead percentage (e.g., 15.00 for 15%)",
                        max_digits=5,
                    ),
                ),
                (
                    "overhead_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Calculated overhead amount",
                        max_digits=14,
                    ),
                ),
                (
                    "margin_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20.00"),
                        help_text="Profit margin percentage (e.g., 20.00 for 20%)",
                        max_digits=5,
                    ),
                ),
                (
                    "margin_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Calculated margin amount",
                        max_digits=14,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Final total (subtotal + overhead + margin)",
                        max_digits=14,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("SENT_TO_CUSTOMER", "Sent to Customer"),
                            ("APPROVED", "Approved by Customer"),
                            ("REJECTED", "Rejected by Customer"),
                            ("REVISED", "Revised/Superseded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "sent_to_customer_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When quotation was sent to customer",
                        null=True,
                    ),
                ),
                (
                    "approved_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When customer approved quotation",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason for customer rejection",
                    ),
                ),
                ("rejected_date", models.DateTimeField(blank=True, null=True)),
                (
                    "revision_number",
                    models.IntegerField(
                        default=1, help_text="Revision number (1, 2, 3...)"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes about this quotation",
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes to include in customer-facing quotation",
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Payment terms (e.g., '30 days net')",
                    ),
                ),
                (
                    "delivery_terms",
                    models.TextField(
                        blank=True, default="", help_text="Delivery terms and timeline"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who recorded customer approval",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        help_text="Job card this quotation is for",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="production.jobcard",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who sent quotation to customer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Newer quotation that replaces this one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="production.quotation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation",
                "verbose_name_plural": "Quotations",
                "db_table": "production_quotation",
                "ordering": ["-quotation_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "line_number",
                    models.IntegerField(help_text="Line sequence number (1, 2, 3...)"),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("CUTTER", "Cutter"),
                            ("LABOR", "Labor"),
                            ("MATERIAL", "Material/Consumable"),
                            ("OVERHEAD", "Overhead"),
                            ("MARGIN", "Margin"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        help_text="Type of line item",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(help_text="Line item description", max_length=500),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0000"),
                        help_text="Quantity (hours for labor, pieces for cutters)",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, help_text="Price per unit", max_digits=12
                    ),
                ),
                (
                    "line_amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Total line amount (quantity × unit_price)",
                        max_digits=14,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Line-specific notes"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item (for cutters and materials)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotation_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Operation (for labor lines)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotation_lines",
                        to="production.operationdefinition",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        help_text="Parent quotation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="production.quotation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quotation Line",
                "verbose_name_plural": "Quotation Lines",
                "db_table": "production_quotation_line",
                "ordering": ["quotation", "line_number"],
            },
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["quotation_number"], name="ix_quot_number"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["job_card"], name="ix_quot_job_card"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["status"], name="ix_quot_status"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["quotation_date"], name="ix_quot_date"),
        ),
        migrations.AlterUniqueTogether(
            name="quotation",
            unique_together={("job_card", "revision_number")},
        ),
        migrations.AddIndex(
            model_name="quotationline",
            index=models.Index(
                fields=["quotation", "line_number"], name="ix_ql_quot_line"
            ),
        ),
        migrations.AddIndex(
            model_name="quotationline",
            index=models.Index(fields=["line_type"], name="ix_ql_type"),
        ),
        migrations.AlterUniqueTogether(
            name="quotationline",
            unique_together={("quotation", "line_number")},
        ),
    ]
