# Generated by Django 5.2.6 on 2025-11-21 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_activitylog_notification'),
        ('engineering', '0001_initial'),
        ('inventory', '0005_remove_bitdesign_created_by_remove_bitdesign_level_and_more'),
        ('production', '0003_quotation_quotationline_quotation_ix_quot_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutterlayout',
            name='design_revision',
            field=models.ForeignKey(help_text='Bit design revision this layout belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cutter_layouts', to='engineering.bitdesignrevision'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='bom_header',
            field=models.ForeignKey(blank=True, help_text='Specific BOM to use (if different from MAT default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_cards', to='engineering.bomheader'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='current_mat',
            field=models.ForeignKey(blank=True, help_text='Current MAT after changes (retrofit, substitution)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_cards_current', to='engineering.bitdesignrevision'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='initial_mat',
            field=models.ForeignKey(blank=True, help_text='Initial MAT used for BOM and expectations', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_cards_initial', to='engineering.bitdesignrevision'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['actual_start_date', 'actual_end_date'], name='ix_jc_actual_times'),
        ),
    ]
