# Generated by Django 5.2.6 on 2025-11-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonconformancereport',
            name='actual_cost_impact',
            field=models.DecimalField(decimal_places=2, default=0, help_text='DEPRECATED: Use finance.NCRFinancialImpact instead', max_digits=12),
        ),
        migrations.AlterField(
            model_name='nonconformancereport',
            name='estimated_cost_impact',
            field=models.DecimalField(decimal_places=2, default=0, help_text='DEPRECATED: Use finance.NCRFinancialImpact instead', max_digits=12),
        ),
        migrations.AlterField(
            model_name='nonconformancereport',
            name='lost_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='DEPRECATED: Use finance.NCRFinancialImpact instead', max_digits=12),
        ),
    ]
