# Generated by Django 5.2.6 on 2025-11-19 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('VIEW', 'Viewed'), ('EXPORT', 'Exported'), ('IMPORT', 'Imported'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('SUBMIT', 'Submitted'), ('CANCEL', 'Cancelled'), ('COMPLETE', 'Completed'), ('ASSIGN', 'Assigned'), ('COMMENT', 'Commented'), ('OTHER', 'Other')], help_text='Type of action performed', max_length=20)),
                ('description', models.TextField(help_text='Description of the action')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of object affected', null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional context data (changes, metadata, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser user agent string')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of object affected', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'core_activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_activi_user_id_0351b4_idx'), models.Index(fields=['content_type', 'object_id'], name='core_activi_content_02b503_idx'), models.Index(fields=['action', '-created_at'], name='core_activi_action_4c98f2_idx'), models.Index(fields=['-created_at'], name='core_activi_created_591ace_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('TASK', 'Task'), ('APPROVAL', 'Approval Required'), ('SYSTEM', 'System')], default='INFO', help_text='Type of notification', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', help_text='Notification priority', max_length=10)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object', null=True)),
                ('action_url', models.CharField(blank=True, default='', help_text='URL for the primary action', max_length=500)),
                ('action_text', models.CharField(blank=True, default='View', help_text='Text for the action button', max_length=50)),
                ('is_read', models.BooleanField(default=False, help_text='Whether user has read this notification')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification expires (optional)', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of related object', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'core_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='core_notifi_user_id_f286cd_idx'), models.Index(fields=['user', 'notification_type'], name='core_notifi_user_id_aa1102_idx'), models.Index(fields=['-created_at'], name='core_notifi_created_f19d5e_idx')],
            },
        ),
    ]
