# Generated by Django 5.2.6 on 2025-11-19 00:22

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_cutterownershipcategory_and_more"),
        ("planning", "0001_initial"),
        (
            "production",
            "0003_quotation_quotationline_quotation_ix_quot_number_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequirementCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Category code (e.g., DATA, DOCUMENT, MATERIAL)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("DATA", "Data/Information"),
                            ("DOCUMENT", "Document/Form"),
                            ("MATERIAL", "Material/Item"),
                            ("INSTRUCTION", "Instruction/Procedure"),
                            ("APPROVAL", "Approval/Sign-off"),
                            ("TOOL_EQUIPMENT", "Tool/Equipment"),
                            ("INSPECTION", "Inspection/Test"),
                            ("PERSONNEL", "Personnel/Skill"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Icon class for UI (e.g., 'bi-file-earmark-text')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Color for UI badges (e.g., 'primary', 'success', 'warning')",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Requirement Category",
                "verbose_name_plural": "Requirement Categories",
                "db_table": "planning_requirement_category",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Instruction title", max_length=200),
                ),
                (
                    "applies_to_type",
                    models.CharField(
                        choices=[
                            ("SERIAL_NUMBER", "Specific Serial Number"),
                            ("MAT_NUMBER", "Specific MAT Number"),
                            ("BIT_TYPE", "Bit Type Family"),
                            ("CUSTOMER", "Customer"),
                            ("OPERATION", "Operation/Process"),
                            ("ALL", "All Jobs"),
                        ],
                        db_index=True,
                        default="ALL",
                        help_text="What type of jobs this instruction applies to",
                        max_length=20,
                    ),
                ),
                (
                    "applies_to_value",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Specific value (SN, MAT#, customer name, operation code, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "instruction_text",
                    models.TextField(
                        help_text="Full instruction text (supports markdown)"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Lower number = higher priority (displayed first)",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Instruction category (Safety, Quality, Process, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "document_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path to PDF or document file",
                        max_length=500,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="External URL for additional resources",
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as critical safety or quality instruction",
                    ),
                ),
                (
                    "requires_acknowledgement",
                    models.BooleanField(
                        default=False,
                        help_text="Operator must acknowledge reading this instruction",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Instruction version number",
                        max_length=20,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when this version becomes effective",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for searching/filtering (e.g., ['welding', 'safety', 'aramco'])",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Technical Instruction",
                "verbose_name_plural": "Technical Instructions",
                "db_table": "planning_technical_instruction",
                "ordering": ["applies_to_type", "priority", "title"],
            },
        ),
        migrations.CreateModel(
            name="RequirementTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Standard Repair Requirements')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of this requirement template",
                    ),
                ),
                (
                    "applies_to_job_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of job types this applies to (e.g., ['REPAIR', 'RETROFIT']). Empty = all types.",
                    ),
                ),
                (
                    "applies_to_customers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of customer codes this applies to. Empty = all customers.",
                    ),
                ),
                (
                    "applies_to_mat_levels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of MAT levels this applies to (e.g., ['L3', 'L4', 'L5']). Empty = all levels.",
                    ),
                ),
                (
                    "applies_to_bit_sizes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of bit sizes this applies to (e.g., ['8.5', '12.25']). Empty = all sizes.",
                    ),
                ),
                (
                    "requirement_text",
                    models.TextField(
                        help_text="Full requirement description (what needs to be done/provided)"
                    ),
                ),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=False,
                        help_text="If True, job cannot proceed until this requirement is met",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="If False, requirement is optional/recommended but not required",
                    ),
                ),
                (
                    "linked_document_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="For DOCUMENT requirements: document type (e.g., 'Drawing', 'Permit')",
                        max_length=100,
                    ),
                ),
                (
                    "auto_complete_trigger",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Manual Only"),
                            ("BOM_AVAILABLE", "BOM Available"),
                            ("EVALUATION_COMPLETE", "Evaluation Complete"),
                            ("ROUTING_COMPLETE", "Routing Complete"),
                            ("QC_APPROVED", "QC Approved"),
                            ("CUSTOMER_APPROVAL", "Customer Approval"),
                        ],
                        default="",
                        help_text="If set, requirement auto-completes when trigger condition is met",
                        max_length=50,
                    ),
                ),
                (
                    "expected_days_from_start",
                    models.IntegerField(
                        blank=True,
                        help_text="Expected days from job start to complete this requirement",
                        null=True,
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Display order in requirements list"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes about this requirement template",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Requirement category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="planning.requirementcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depends_on_templates",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Other requirement templates that must be completed first",
                        related_name="dependent_templates",
                        to="planning.requirementtemplate",
                    ),
                ),
                (
                    "linked_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="For MATERIAL requirements: link to specific item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirement_templates",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_instruction",
                    models.ForeignKey(
                        blank=True,
                        help_text="For INSTRUCTION requirements: link to technical instruction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirement_templates",
                        to="planning.technicalinstruction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requirement Template",
                "verbose_name_plural": "Requirement Templates",
                "db_table": "planning_requirement_template",
                "ordering": ["category", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="JobRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "requirement_text",
                    models.TextField(help_text="Full requirement description"),
                ),
                (
                    "is_blocking",
                    models.BooleanField(
                        default=False,
                        help_text="If True, job cannot proceed until this requirement is met",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True, help_text="If False, requirement is optional"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("WAITING_DEPENDENCY", "Waiting on Dependency"),
                            ("BLOCKED", "Blocked"),
                            ("COMPLETED", "Completed"),
                            ("WAIVED", "Waived/N/A"),
                            ("FAILED", "Failed/Rejected"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "started_date",
                    models.DateTimeField(
                        blank=True, help_text="When requirement work started", null=True
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When requirement was completed",
                        null=True,
                    ),
                ),
                (
                    "verified_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When requirement completion was verified",
                        null=True,
                    ),
                ),
                (
                    "waived_date",
                    models.DateTimeField(
                        blank=True, help_text="When requirement was waived", null=True
                    ),
                ),
                (
                    "waiver_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason for waiving requirement",
                    ),
                ),
                (
                    "linked_document_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="For DOCUMENT: path to uploaded document file",
                        max_length=500,
                    ),
                ),
                (
                    "blocked_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="If status=BLOCKED, why is it blocked?",
                    ),
                ),
                (
                    "blocked_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When requirement became blocked",
                        null=True,
                    ),
                ),
                (
                    "expected_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected date to complete this requirement",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes about this requirement",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Display order in requirements list"
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who completed this requirement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirements_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Other requirements that must be completed first",
                        related_name="dependent_requirements",
                        to="planning.jobrequirement",
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        help_text="Job card this requirement belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="production.jobcard",
                    ),
                ),
                (
                    "linked_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="For MATERIAL: actual item that satisfies requirement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_requirements",
                        to="inventory.item",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who started working on this requirement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirements_started",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who verified completion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requirements_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "waived_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who waived this requirement",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_requirements_waived",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Requirement category",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_requirements",
                        to="planning.requirementcategory",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template this was created from (null if manually added)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instances",
                        to="planning.requirementtemplate",
                    ),
                ),
                (
                    "linked_instruction",
                    models.ForeignKey(
                        blank=True,
                        help_text="For INSTRUCTION: technical instruction followed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_requirements",
                        to="planning.technicalinstruction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Requirement",
                "verbose_name_plural": "Job Requirements",
                "db_table": "planning_job_requirement",
                "ordering": ["job_card", "sort_order", "category", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="WIPDashboardMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When this snapshot was taken",
                    ),
                ),
                (
                    "total_wip",
                    models.IntegerField(
                        help_text="Total bits in work (all stages except terminal)"
                    ),
                ),
                (
                    "total_on_hold",
                    models.IntegerField(default=0, help_text="Bits on hold"),
                ),
                (
                    "total_priority",
                    models.IntegerField(default=0, help_text="Priority bits"),
                ),
                (
                    "stage_counts",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Count by stage.\n        Example: {"EVAL_QUEUE": 15, "EVALUATING": 8, "REPAIR_QUEUE": 22, ...}\n        ',
                    ),
                ),
                (
                    "bottleneck_stages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Stages exceeding warning threshold",
                        size=None,
                    ),
                ),
                (
                    "average_age_by_stage",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Average hours in each stage.\n        Example: {"EVAL_QUEUE": 24.5, "EVALUATING": 8.2, ...}\n        ',
                    ),
                ),
                (
                    "completed_since_last",
                    models.IntegerField(
                        default=0, help_text="Bits completed since last snapshot"
                    ),
                ),
                (
                    "new_since_last",
                    models.IntegerField(
                        default=0, help_text="Bits added since last snapshot"
                    ),
                ),
            ],
            options={
                "verbose_name": "WIP Dashboard Metrics",
                "verbose_name_plural": "WIP Dashboard Metrics",
                "db_table": "planning_wip_dashboard_metrics",
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(fields=["snapshot_date"], name="ix_wdm_snapshot")
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "stage_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique stage code (e.g., EVAL_QUEUE, REPAIRING)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "stage_name",
                    models.CharField(
                        help_text="Display name for stage", max_length=100
                    ),
                ),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("QUEUE", "Queue/Waiting"),
                            ("ACTIVE", "Active Work"),
                            ("INSPECTION", "Inspection/QC"),
                            ("HOLD", "On Hold"),
                            ("COMPLETE", "Complete/Terminal"),
                        ],
                        help_text="Type of stage (affects visualization)",
                        max_length=20,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=10, help_text="Display order in kanban (left to right)"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#3498db",
                        help_text="Stage color (hex code for visual board)",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-circle",
                        help_text="FontAwesome icon class",
                        max_length=50,
                    ),
                ),
                (
                    "capacity_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Max bits allowed in this stage (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "warn_threshold",
                    models.IntegerField(
                        blank=True,
                        help_text="Warn when count exceeds this (bottleneck detection)",
                        null=True,
                    ),
                ),
                (
                    "average_duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected average time in this stage (for forecasting)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "auto_advance_conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        Conditions to auto-advance to next stage.\n        Example: {"evaluation_complete": true, "quotation_approved": true}\n        ',
                    ),
                ),
                (
                    "requires_assignment",
                    models.BooleanField(
                        default=False,
                        help_text="Must assign to user/team before entering this stage",
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False, help_text="Requires approval to exit this stage"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Stage is active and shown on board"
                    ),
                ),
                (
                    "is_terminal",
                    models.BooleanField(
                        default=False,
                        help_text="Terminal stage (no further progression)",
                    ),
                ),
                (
                    "allowed_next_stages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Stages that can follow this one",
                        related_name="allowed_previous_stages",
                        to="planning.workflowstage",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Stage",
                "verbose_name_plural": "Workflow Stages",
                "db_table": "planning_workflow_stage",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="VisualBoardLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "layout_name",
                    models.CharField(
                        help_text="Name for this board view", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Description of this view"
                    ),
                ),
                (
                    "filter_rules",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Filter criteria for bits shown on this board.\n        Example:\n        {\n            "job_types": ["REPAIR", "RETROFIT"],\n            "customers": ["ENO", "LSTK"],\n            "priority_only": true,\n            "assigned_to_me": true,\n            "max_age_days": 7,\n            "stages": ["EVAL_QUEUE", "EVALUATING", "REPAIR_QUEUE"]\n        }\n        ',
                    ),
                ),
                (
                    "display_settings",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Visual display settings.\n        Example:\n        {\n            "group_by": "customer",\n            "sort_by": "entered_at",\n            "show_age": true,\n            "show_assignment": true,\n            "compact_mode": false,\n            "color_by": "priority"\n        }\n        ',
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False, help_text="Shared with team/public"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default board for this user"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this layout",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_layouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who can see this layout",
                        related_name="shared_board_layouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visible_stages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Stages shown on this board (empty = all active stages)",
                        related_name="visible_in_layouts",
                        to="planning.workflowstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visual Board Layout",
                "verbose_name_plural": "Visual Board Layouts",
                "db_table": "planning_visual_board_layout",
                "ordering": ["created_by", "layout_name"],
            },
        ),
        migrations.CreateModel(
            name="BitWorkflowPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "entered_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When bit entered this stage",
                    ),
                ),
                (
                    "exited_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When bit exited this stage",
                        null=True,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="True if bit is currently in this stage",
                    ),
                ),
                (
                    "board_column",
                    models.IntegerField(
                        blank=True,
                        help_text="Column position on kanban board (for persistence)",
                        null=True,
                    ),
                ),
                (
                    "board_row",
                    models.IntegerField(
                        blank=True,
                        help_text="Row position on kanban board (for persistence)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes about this stage transition",
                    ),
                ),
                (
                    "hold_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason if bit is on hold in this stage",
                    ),
                ),
                (
                    "expected_completion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expected completion time for this stage",
                        null=True,
                    ),
                ),
                (
                    "is_on_hold",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Bit is on hold in this stage",
                    ),
                ),
                (
                    "is_priority",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Priority/expedite flag"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to work on this bit in this stage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_bits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        help_text="Job card being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_positions",
                        to="production.jobcard",
                    ),
                ),
                (
                    "moved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who moved bit to this stage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_moves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "serial_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Serial unit (if known)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_positions",
                        to="inventory.serialunit",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        help_text="Current or historical stage",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bit_positions",
                        to="planning.workflowstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bit Workflow Position",
                "verbose_name_plural": "Bit Workflow Positions",
                "db_table": "planning_bit_workflow_position",
                "ordering": ["-entered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="technicalinstruction",
            index=models.Index(
                fields=["applies_to_type", "applies_to_value"], name="ix_ti_type_value"
            ),
        ),
        migrations.AddIndex(
            model_name="technicalinstruction",
            index=models.Index(
                fields=["is_active", "priority"], name="ix_ti_active_pri"
            ),
        ),
        migrations.AddIndex(
            model_name="requirementtemplate",
            index=models.Index(
                fields=["category", "is_active"], name="ix_rt_cat_active"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrequirement",
            index=models.Index(fields=["job_card", "status"], name="ix_jr_job_status"),
        ),
        migrations.AddIndex(
            model_name="jobrequirement",
            index=models.Index(
                fields=["status", "is_blocking"], name="ix_jr_status_block"
            ),
        ),
        migrations.AddIndex(
            model_name="jobrequirement",
            index=models.Index(fields=["completed_date"], name="ix_jr_completed"),
        ),
        migrations.AddIndex(
            model_name="workflowstage",
            index=models.Index(fields=["stage_code"], name="ix_ws_code"),
        ),
        migrations.AddIndex(
            model_name="workflowstage",
            index=models.Index(fields=["display_order"], name="ix_ws_order"),
        ),
        migrations.AlterUniqueTogether(
            name="visualboardlayout",
            unique_together={("created_by", "layout_name")},
        ),
        migrations.AddIndex(
            model_name="bitworkflowposition",
            index=models.Index(
                fields=["job_card", "is_current"], name="ix_bwp_jc_current"
            ),
        ),
        migrations.AddIndex(
            model_name="bitworkflowposition",
            index=models.Index(
                fields=["stage", "is_current"], name="ix_bwp_stage_current"
            ),
        ),
        migrations.AddIndex(
            model_name="bitworkflowposition",
            index=models.Index(fields=["entered_at"], name="ix_bwp_entered"),
        ),
        migrations.AddIndex(
            model_name="bitworkflowposition",
            index=models.Index(fields=["assigned_to"], name="ix_bwp_assigned"),
        ),
        migrations.AddIndex(
            model_name="bitworkflowposition",
            index=models.Index(fields=["is_priority"], name="ix_bwp_priority"),
        ),
    ]
