# Generated by Django 5.2.6 on 2025-11-23 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("hr", "0005_assettype_hrasset_assetassignment_hrcontract_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        help_text="Unique request number", max_length=50, unique=True
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("certificate", "Employment Certificate"),
                            ("salary_certificate", "Salary Certificate"),
                            ("document_copy", "Document Copy"),
                            ("info_update", "Personal Information Update"),
                            ("leave_balance", "Leave Balance Inquiry"),
                            ("other", "Other Request"),
                        ],
                        help_text="Type of request",
                        max_length=30,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Request subject", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the request"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        help_text="Request priority",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="submitted",
                        help_text="Current status",
                        max_length=20,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Supporting document or file",
                        null=True,
                        upload_to="hr_portal/requests/",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of related object", null=True
                    ),
                ),
                (
                    "response",
                    models.TextField(blank=True, help_text="Response from HR"),
                ),
                (
                    "response_attachment",
                    models.FileField(
                        blank=True,
                        help_text="Response document (e.g., issued certificate)",
                        null=True,
                        upload_to="hr_portal/responses/",
                    ),
                ),
                (
                    "submitted_date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date request was submitted"
                    ),
                ),
                (
                    "reviewed_date",
                    models.DateTimeField(
                        blank=True, help_text="Date request was reviewed", null=True
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True, help_text="Date request was completed", null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of related object",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee who submitted this request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_requests",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="HR user who reviewed this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_employee_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Request",
                "verbose_name_plural": "Employee Requests",
                "db_table": "hr_employee_request",
                "ordering": ["-submitted_date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "status"],
                        name="hr_employee_employe_8776ee_idx",
                    ),
                    models.Index(
                        fields=["request_type"], name="hr_employee_request_13cf99_idx"
                    ),
                    models.Index(
                        fields=["status"], name="hr_employee_status_a77c16_idx"
                    ),
                    models.Index(
                        fields=["submitted_date"], name="hr_employee_submitt_8bd3c6_idx"
                    ),
                ],
            },
        ),
    ]
