# Generated by Django 5.2.6 on 2025-11-17 10:34

import django.db.models.deletion
import django.utils.timezone
import floor_app.operations.hr.models.leave
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("CONTRACT", "Employment Contract"),
                            ("ID_DOCUMENT", "ID Document (Iqama/National ID)"),
                            ("PASSPORT", "Passport"),
                            ("VISA", "Visa"),
                            ("WORK_PERMIT", "Work Permit"),
                            ("CERTIFICATE", "Professional Certificate"),
                            ("QUALIFICATION", "Educational Qualification"),
                            ("MEDICAL", "Medical Certificate/Report"),
                            ("INSURANCE", "Insurance Document"),
                            ("PERFORMANCE", "Performance Review"),
                            ("LETTER", "Official Letter"),
                            ("OTHER", "Other Document"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "document_number",
                    models.CharField(
                        blank=True,
                        help_text="Document number/reference",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VALID", "Valid"),
                            ("EXPIRED", "Expired"),
                            ("EXPIRING_SOON", "Expiring Soon"),
                            ("PENDING_RENEWAL", "Pending Renewal"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="VALID",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Expiry date (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "renewal_reminder_days",
                    models.IntegerField(
                        default=30, help_text="Days before expiry to send reminder"
                    ),
                ),
                ("issuing_authority", models.CharField(blank=True, max_length=200)),
                ("issuing_country", models.CharField(blank=True, max_length=100)),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to uploaded document",
                        max_length=500,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_by_id", models.BigIntegerField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                ("is_confidential", models.BooleanField(default=False)),
                (
                    "access_restricted",
                    models.BooleanField(
                        default=False, help_text="Restrict access to HR only"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, help_text="Mandatory document for employment"
                    ),
                ),
                (
                    "compliance_category",
                    models.CharField(
                        blank=True,
                        help_text="Compliance category (Saudi Labor Law, etc.)",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Document",
                "verbose_name_plural": "Employee Documents",
                "db_table": "hr_employee_document",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRenewal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                ("request_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "new_expiry_date",
                    models.DateField(
                        blank=True, help_text="New expiry date after renewal", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                (
                    "renewal_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "paid_by",
                    models.CharField(
                        choices=[
                            ("COMPANY", "Company"),
                            ("EMPLOYEE", "Employee"),
                            ("SHARED", "Shared"),
                        ],
                        default="COMPANY",
                        max_length=20,
                    ),
                ),
                ("new_document_number", models.CharField(blank=True, max_length=100)),
                ("new_file_path", models.CharField(blank=True, max_length=500)),
                ("processed_by_id", models.BigIntegerField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renewals",
                        to="hr.employeedocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Renewal",
                "verbose_name_plural": "Document Renewals",
                "db_table": "hr_document_renewal",
                "ordering": ["-request_date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "registered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "registered_by_id",
                    models.BigIntegerField(
                        blank=True, help_text="Registered by (manager/HR)", null=True
                    ),
                ),
                ("attended", models.BooleanField(default=False)),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Percentage of sessions attended",
                        max_digits=5,
                    ),
                ),
                (
                    "assessment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Assessment score percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                ("attempts", models.IntegerField(default=1)),
                ("certificate_number", models.CharField(blank=True, max_length=100)),
                ("certificate_issued_date", models.DateField(blank=True, null=True)),
                ("certificate_expiry_date", models.DateField(blank=True, null=True)),
                ("certificate_path", models.CharField(blank=True, max_length=500)),
                (
                    "feedback_rating",
                    models.IntegerField(blank=True, help_text="Rating 1-5", null=True),
                ),
                ("feedback_comments", models.TextField(blank=True)),
                (
                    "cost_incurred",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed/Did Not Complete"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_records",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Training",
                "verbose_name_plural": "Employee Training Records",
                "db_table": "hr_employee_training",
                "ordering": ["-training_session__start_date"],
            },
        ),
        migrations.CreateModel(
            name="ExpiryAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                ("alert_date", models.DateField(default=django.utils.timezone.now)),
                ("days_before_expiry", models.IntegerField()),
                ("notified_employee", models.BooleanField(default=False)),
                ("employee_notified_at", models.DateTimeField(blank=True, null=True)),
                ("notified_hr", models.BooleanField(default=False)),
                ("hr_notified_at", models.DateTimeField(blank=True, null=True)),
                ("notified_manager", models.BooleanField(default=False)),
                ("manager_notified_at", models.DateTimeField(blank=True, null=True)),
                ("action_taken", models.TextField(blank=True)),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_by_id", models.BigIntegerField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiry_alerts",
                        to="hr.employeedocument",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expiry Alert",
                "verbose_name_plural": "Expiry Alerts",
                "db_table": "hr_expiry_alert",
                "ordering": ["-alert_date"],
            },
        ),
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual Leave"),
                            ("SICK", "Sick Leave"),
                            ("MATERNITY", "Maternity Leave"),
                            ("PATERNITY", "Paternity Leave"),
                            ("BEREAVEMENT", "Bereavement Leave"),
                            ("HAJJ", "Hajj/Pilgrimage Leave"),
                            ("MARRIAGE", "Marriage Leave"),
                            ("UNPAID", "Unpaid Leave"),
                            ("EMERGENCY", "Emergency Leave"),
                            ("COMPENSATORY", "Compensatory Off"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "annual_entitlement_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Annual entitlement in days",
                        max_digits=5,
                    ),
                ),
                (
                    "max_accumulation_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Maximum days that can be accumulated",
                        max_digits=5,
                    ),
                ),
                (
                    "carry_forward_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Days that can be carried forward",
                        max_digits=5,
                    ),
                ),
                (
                    "carry_forward_expiry_months",
                    models.IntegerField(
                        default=12, help_text="Months after which carry forward expires"
                    ),
                ),
                (
                    "minimum_notice_days",
                    models.IntegerField(
                        default=0, help_text="Minimum days notice required"
                    ),
                ),
                (
                    "maximum_consecutive_days",
                    models.IntegerField(
                        default=30, help_text="Maximum consecutive days allowed"
                    ),
                ),
                (
                    "minimum_days_per_request",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.5,
                        help_text="Minimum days per request (0.5 for half day)",
                        max_digits=3,
                    ),
                ),
                (
                    "accrual_type",
                    models.CharField(
                        choices=[
                            ("UPFRONT", "Upfront at start of year"),
                            ("MONTHLY", "Monthly accrual"),
                            ("QUARTERLY", "Quarterly accrual"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("prorate_for_new_joiners", models.BooleanField(default=True)),
                ("prorate_for_leavers", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=True)),
                (
                    "auto_approve_below_days",
                    models.IntegerField(
                        default=0,
                        help_text="Auto-approve requests below this number of days (0 = always require approval)",
                    ),
                ),
                ("requires_medical_certificate", models.BooleanField(default=False)),
                (
                    "medical_certificate_after_days",
                    models.IntegerField(
                        default=2,
                        help_text="Medical certificate required after this many days",
                    ),
                ),
                ("allows_encashment", models.BooleanField(default=False)),
                ("max_encashment_days", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Policy",
                "verbose_name_plural": "Leave Policies",
                "db_table": "hr_leave_policy",
                "ordering": ["leave_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "year",
                    models.IntegerField(
                        db_index=True,
                        default=floor_app.operations.hr.models.leave.get_current_year,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Balance at start of year",
                        max_digits=6,
                    ),
                ),
                (
                    "accrued",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Days accrued during the year",
                        max_digits=6,
                    ),
                ),
                (
                    "used",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Days used", max_digits=6
                    ),
                ),
                (
                    "pending",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Days in pending requests",
                        max_digits=6,
                    ),
                ),
                (
                    "adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Manual adjustments",
                        max_digits=6,
                    ),
                ),
                (
                    "encashed",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Days encashed",
                        max_digits=6,
                    ),
                ),
                (
                    "carry_forward_from_previous",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Carried forward from previous year",
                        max_digits=6,
                    ),
                ),
                ("adjustment_reason", models.TextField(blank=True)),
                ("last_accrual_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="hr.leavepolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Balance",
                "verbose_name_plural": "Leave Balances",
                "db_table": "hr_leave_balance",
                "ordering": ["-year", "employee"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "request_number",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "total_days",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total leave days requested",
                        max_digits=5,
                    ),
                ),
                (
                    "is_half_day_start",
                    models.BooleanField(
                        default=False, help_text="Start date is half day"
                    ),
                ),
                (
                    "is_half_day_end",
                    models.BooleanField(
                        default=False, help_text="End date is half day"
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for leave")),
                (
                    "contact_during_leave",
                    models.CharField(
                        blank=True,
                        help_text="Contact number during leave",
                        max_length=200,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approver_id", models.BigIntegerField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True)),
                ("rejected_by_id", models.BigIntegerField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                (
                    "coverage_employee_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Employee covering during absence",
                        null=True,
                    ),
                ),
                ("handover_notes", models.TextField(blank=True)),
                ("attachment_path", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "leave_policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="hr.leavepolicy",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Request",
                "verbose_name_plural": "Leave Requests",
                "db_table": "hr_leave_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OvertimeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "request_number",
                    models.CharField(db_index=True, max_length=30, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "overtime_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular Overtime"),
                            ("WEEKEND", "Weekend Overtime"),
                            ("HOLIDAY", "Holiday Overtime"),
                            ("NIGHT", "Night Shift Overtime"),
                        ],
                        default="REGULAR",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "planned_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Planned overtime hours",
                        max_digits=4,
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual overtime hours worked",
                        max_digits=4,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "work_description",
                    models.TextField(
                        blank=True, help_text="Description of work done during overtime"
                    ),
                ),
                ("approver_id", models.BigIntegerField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True)),
                ("rejected_by_id", models.BigIntegerField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "rate_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        help_text="Overtime rate multiplier (1.5x, 2x, etc.)",
                        max_digits=3,
                    ),
                ),
                (
                    "is_compensatory_off",
                    models.BooleanField(
                        default=False,
                        help_text="Convert to compensatory off instead of payment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_requests",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Overtime Request",
                "verbose_name_plural": "Overtime Requests",
                "db_table": "hr_overtime_request",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SkillMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                ("skill_name", models.CharField(max_length=200)),
                (
                    "skill_category",
                    models.CharField(
                        choices=[
                            ("TECHNICAL", "Technical"),
                            ("SOFTWARE", "Software/Tools"),
                            ("LANGUAGE", "Language"),
                            ("CERTIFICATION", "Certification"),
                            ("SOFT_SKILL", "Soft Skill"),
                            ("DOMAIN", "Domain Knowledge"),
                        ],
                        default="TECHNICAL",
                        max_length=50,
                    ),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("BEGINNER", "Beginner"),
                            ("INTERMEDIATE", "Intermediate"),
                            ("ADVANCED", "Advanced"),
                            ("EXPERT", "Expert"),
                        ],
                        default="BEGINNER",
                        max_length=20,
                    ),
                ),
                (
                    "proficiency_score",
                    models.IntegerField(default=1, help_text="Score 1-5"),
                ),
                (
                    "years_of_experience",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                ("verified", models.BooleanField(default=False)),
                ("verified_by_id", models.BigIntegerField(blank=True, null=True)),
                ("verification_date", models.DateField(blank=True, null=True)),
                (
                    "verification_method",
                    models.CharField(
                        blank=True,
                        help_text="Assessment, certification, manager review, etc.",
                        max_length=50,
                    ),
                ),
                ("last_used_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "related_training",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skills_gained",
                        to="hr.employeetraining",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Entry",
                "verbose_name_plural": "Skill Matrix",
                "db_table": "hr_skill_matrix",
                "ordering": ["employee", "skill_category", "skill_name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("ONBOARDING", "Onboarding/Induction"),
                            ("TECHNICAL", "Technical Training"),
                            ("SAFETY", "Health & Safety"),
                            ("COMPLIANCE", "Compliance & Regulatory"),
                            ("SOFT_SKILLS", "Soft Skills"),
                            ("LEADERSHIP", "Leadership & Management"),
                            ("CERTIFICATION", "Professional Certification"),
                            ("EXTERNAL", "External Training"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total duration in hours",
                        max_digits=5,
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(default=1, help_text="Duration in days"),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Training provider/instructor",
                        max_length=200,
                    ),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=True, help_text="Internal or external training"
                    ),
                ),
                (
                    "prerequisites",
                    models.TextField(
                        blank=True, help_text="Prerequisites for this training"
                    ),
                ),
                (
                    "target_audience",
                    models.TextField(blank=True, help_text="Target audience/positions"),
                ),
                ("max_participants", models.IntegerField(default=20)),
                ("has_assessment", models.BooleanField(default=False)),
                (
                    "passing_score",
                    models.IntegerField(
                        default=70, help_text="Minimum passing score percentage"
                    ),
                ),
                ("grants_certificate", models.BooleanField(default=False)),
                (
                    "certificate_validity_months",
                    models.IntegerField(
                        default=0,
                        help_text="Months before certificate expires (0 = no expiry)",
                    ),
                ),
                (
                    "cost_per_person",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="SAR", max_length=3)),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, help_text="Mandatory for certain positions"
                    ),
                ),
                (
                    "mandatory_for_positions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of position IDs this is mandatory for",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("materials_path", models.CharField(blank=True, max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Program",
                "verbose_name_plural": "Training Programs",
                "db_table": "hr_training_program",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "is_deleted",
                    models.BooleanField(db_index=True, default=False, editable=False),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("session_code", models.CharField(max_length=30, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed/Did Not Complete"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=15,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(max_length=200)),
                ("is_virtual", models.BooleanField(default=False)),
                ("virtual_link", models.URLField(blank=True)),
                ("instructor_name", models.CharField(max_length=200)),
                ("instructor_contact", models.CharField(blank=True, max_length=100)),
                ("registered_count", models.IntegerField(default=0)),
                ("attended_count", models.IntegerField(default=0)),
                ("passed_count", models.IntegerField(default=0)),
                ("materials_distributed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("feedback_summary", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="hr.trainingprogram",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Session",
                "verbose_name_plural": "Training Sessions",
                "db_table": "hr_training_session",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="employeetraining",
            name="training_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="hr.trainingsession",
            ),
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late Arrival"),
                            ("EARLY_LEAVE", "Early Leave"),
                            ("HALF_DAY", "Half Day"),
                            ("ON_LEAVE", "On Leave"),
                            ("HOLIDAY", "Holiday"),
                            ("WEEKEND", "Weekend"),
                        ],
                        db_index=True,
                        default="ABSENT",
                        max_length=15,
                    ),
                ),
                (
                    "scheduled_start",
                    models.TimeField(
                        blank=True, help_text="Scheduled start time", null=True
                    ),
                ),
                (
                    "scheduled_end",
                    models.TimeField(
                        blank=True, help_text="Scheduled end time", null=True
                    ),
                ),
                (
                    "actual_start",
                    models.TimeField(
                        blank=True, help_text="Actual check-in time", null=True
                    ),
                ),
                (
                    "actual_end",
                    models.TimeField(
                        blank=True, help_text="Actual check-out time", null=True
                    ),
                ),
                ("break_start", models.TimeField(blank=True, null=True)),
                ("break_end", models.TimeField(blank=True, null=True)),
                ("total_break_minutes", models.IntegerField(default=0)),
                (
                    "scheduled_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=8,
                        help_text="Scheduled work hours",
                        max_digits=4,
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Actual hours worked",
                        max_digits=4,
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Overtime hours worked",
                        max_digits=4,
                    ),
                ),
                (
                    "late_minutes",
                    models.IntegerField(default=0, help_text="Minutes late to work"),
                ),
                (
                    "early_leave_minutes",
                    models.IntegerField(default=0, help_text="Minutes left early"),
                ),
                ("location_name", models.CharField(blank=True, max_length=200)),
                ("is_remote_work", models.BooleanField(default=False)),
                ("supervisor_notes", models.TextField(blank=True)),
                ("employee_notes", models.TextField(blank=True)),
                ("check_in_qcode_id", models.BigIntegerField(blank=True, null=True)),
                ("check_out_qcode_id", models.BigIntegerField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_by_id", models.BigIntegerField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "db_table": "hr_attendance_record",
                "ordering": ["-date", "employee"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"], name="ix_attendance_emp_date"
                    ),
                    models.Index(
                        fields=["date", "status"], name="ix_attendance_date_status"
                    ),
                ],
                "unique_together": {("employee", "date")},
            },
        ),
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                ("year", models.IntegerField(db_index=True)),
                ("month", models.IntegerField(db_index=True)),
                ("total_working_days", models.IntegerField(default=0)),
                ("days_present", models.IntegerField(default=0)),
                ("days_absent", models.IntegerField(default=0)),
                ("days_late", models.IntegerField(default=0)),
                ("days_early_leave", models.IntegerField(default=0)),
                ("days_on_leave", models.IntegerField(default=0)),
                (
                    "days_half_day",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "total_scheduled_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_actual_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "total_overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("total_late_minutes", models.IntegerField(default=0)),
                ("total_early_leave_minutes", models.IntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "punctuality_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "last_calculated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_summaries",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Summary",
                "verbose_name_plural": "Attendance Summaries",
                "db_table": "hr_attendance_summary",
                "ordering": ["-year", "-month", "employee"],
                "unique_together": {("employee", "year", "month")},
            },
        ),
        migrations.AddIndex(
            model_name="employeedocument",
            index=models.Index(
                fields=["employee", "document_type"], name="ix_doc_emp_type"
            ),
        ),
        migrations.AddIndex(
            model_name="employeedocument",
            index=models.Index(fields=["expiry_date"], name="ix_doc_expiry"),
        ),
        migrations.AlterUniqueTogether(
            name="leavebalance",
            unique_together={("employee", "leave_policy", "year")},
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["employee", "status"], name="ix_leavereq_emp_status"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date", "end_date"], name="ix_leavereq_dates"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skillmatrix",
            unique_together={("employee", "skill_name")},
        ),
        migrations.AlterUniqueTogether(
            name="employeetraining",
            unique_together={("employee", "training_session")},
        ),
    ]
