# Generated by Django 5.2.6 on 2025-11-17 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hr', '0002_employeedocument_documentrenewal_employeetraining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hremployee',
            name='report_to',
        ),
        migrations.AddField(
            model_name='department',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Cost center for this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='core.costcenter'),
        ),
        migrations.AddField(
            model_name='department',
            name='erp_department_code',
            field=models.CharField(blank=True, help_text='ERP Department Code', max_length=50),
        ),
        migrations.AddField(
            model_name='hremployee',
            name='grade',
            field=models.CharField(blank=True, help_text='Employee grade/level', max_length=20),
        ),
        migrations.AddField(
            model_name='hremployee',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Direct supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='hr.hremployee'),
        ),
        migrations.AlterField(
            model_name='hremployee',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Employee cost center', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.costcenter'),
        ),
    ]
