# Generated by Django 5.2.6 on 2025-11-19 04:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_hremployee_report_to_department_cost_center_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicy',
            name='leave_type',
            field=models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('MATERNITY', 'Maternity Leave (10 weeks)'), ('PATERNITY', 'Paternity Leave'), ('NEWBORN', 'Newborn Care Leave (3 days - KSA)'), ('BEREAVEMENT', 'Bereavement Leave (General)'), ('BEREAVEMENT_SPOUSE', 'Bereavement - Spouse (5 days - KSA)'), ('BEREAVEMENT_PARENT', 'Bereavement - Parent (5 days - KSA)'), ('BEREAVEMENT_CHILD', 'Bereavement - Child (5 days - KSA)'), ('BEREAVEMENT_SIBLING', 'Bereavement - Sibling (3 days - KSA)'), ('BEREAVEMENT_GRANDPARENT', 'Bereavement - Grandparent (3 days - KSA)'), ('HAJJ', 'Hajj Pilgrimage (Once during employment - KSA)'), ('OMRA', 'Omra/Umrah Pilgrimage (Unpaid - KSA)'), ('EXIT_REENTRY', 'Exit/Re-entry Visa Leave (KSA)'), ('MARRIAGE', 'Marriage Leave'), ('UNPAID', 'Unpaid Leave'), ('EMERGENCY', 'Emergency Leave'), ('COMPENSATORY', 'Compensatory Time Off'), ('STUDY', 'Study/Education Leave')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='AttendanceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('configuration_name', models.CharField(default='Default Attendance Policy', max_length=100)),
                ('standard_working_hours_per_day', models.DecimalField(decimal_places=2, default=8.0, help_text='Standard working hours per day (KSA: 8 hours)', max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('standard_working_hours_per_week', models.DecimalField(decimal_places=2, default=48.0, help_text='Standard working hours per week (KSA: 48 hours)', max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(70)])),
                ('ramadan_working_hours_per_day', models.DecimalField(decimal_places=2, default=6.0, help_text='Working hours during Ramadan (KSA: 6 hours for Muslims)', max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('apply_ramadan_hours', models.BooleanField(default=True, help_text='Automatically apply reduced hours during Ramadan')),
                ('late_arrival_grace_minutes', models.IntegerField(default=5, help_text='Grace period for late arrival (minutes)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('early_departure_grace_minutes', models.IntegerField(default=5, help_text='Grace period for early departure (minutes)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('default_break_duration_minutes', models.IntegerField(default=60, help_text='Default break/lunch duration (minutes)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)])),
                ('break_time_paid', models.BooleanField(default=False, help_text='Whether break time is included in paid hours')),
                ('minor_delay_threshold_minutes', models.IntegerField(default=15, help_text='Threshold for minor delay (warning only)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('major_delay_threshold_minutes', models.IntegerField(default=30, help_text='Threshold for major delay (disciplinary action)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)])),
                ('consecutive_absences_trigger', models.IntegerField(default=3, help_text='Number of consecutive absences to trigger alert', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('allow_manual_entry', models.BooleanField(default=True, help_text='Allow manual attendance entry for employees without punch machines')),
                ('require_supervisor_approval_manual_entry', models.BooleanField(default=True, help_text='Manual entries require supervisor approval')),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Configuration',
                'verbose_name_plural': 'Attendance Configurations',
                'db_table': 'hr_attendance_configuration',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='OvertimeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active at a time')),
                ('configuration_name', models.CharField(default='Default Overtime Policy', max_length=100)),
                ('max_overtime_hours_per_day', models.DecimalField(decimal_places=2, default=3.0, help_text='Maximum overtime hours allowed per day (KSA default: 3)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('max_overtime_hours_per_week', models.DecimalField(decimal_places=2, default=15.0, help_text='Maximum overtime hours allowed per week (KSA default: 15)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('max_overtime_hours_per_month', models.DecimalField(decimal_places=2, default=30.0, help_text='Maximum overtime hours allowed per month (KSA default: 30)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('max_overtime_hours_per_quarter', models.DecimalField(decimal_places=2, default=90.0, help_text='Maximum overtime hours allowed per quarter (KSA default: 90)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('regular_overtime_rate', models.DecimalField(decimal_places=2, default=1.5, help_text='Pay rate multiplier for regular overtime (KSA default: 1.5x = 150%)', max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('weekend_overtime_rate', models.DecimalField(decimal_places=2, default=1.5, help_text='Pay rate multiplier for weekend overtime (KSA default: 1.5x + compensatory day)', max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('holiday_overtime_rate', models.DecimalField(decimal_places=2, default=2.0, help_text='Pay rate multiplier for holiday overtime (KSA default: 2.0x = 200%)', max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('night_shift_overtime_rate', models.DecimalField(decimal_places=2, default=1.5, help_text='Pay rate multiplier for night shift overtime (KSA default: 1.5x)', max_digits=4, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('weekend_work_requires_compensatory_day', models.BooleanField(default=True, help_text='KSA: Weekend work requires compensatory day off in addition to pay')),
                ('requires_manager_approval', models.BooleanField(default=True, help_text='Overtime must be pre-approved by manager')),
                ('requires_hr_approval', models.BooleanField(default=False, help_text='Overtime requires HR approval in addition to manager')),
                ('allow_retroactive_requests', models.BooleanField(default=False, help_text='Allow overtime requests after work is completed')),
                ('max_days_advance_request', models.IntegerField(default=30, help_text='Maximum days in advance for overtime requests', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('night_shift_start_time', models.TimeField(default='22:00', help_text='Start time for night shift (KSA typically 22:00-06:00)')),
                ('night_shift_end_time', models.TimeField(default='06:00', help_text='End time for night shift')),
                ('policy_notes', models.TextField(blank=True, help_text='Additional policy notes and guidelines')),
                ('effective_from', models.DateField(default=django.utils.timezone.now, help_text='Date when this configuration becomes effective')),
                ('effective_to', models.DateField(blank=True, help_text='Date when this configuration expires (optional)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overtime Configuration',
                'verbose_name_plural': 'Overtime Configurations',
                'db_table': 'hr_overtime_configuration',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='DelayIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('scheduled_time', models.TimeField(help_text='Scheduled arrival time')),
                ('actual_time', models.TimeField(help_text='Actual arrival time')),
                ('delay_minutes', models.IntegerField(default=0, help_text='Minutes late (calculated automatically)')),
                ('delay_reason', models.CharField(choices=[('TRAFFIC', 'Traffic Congestion'), ('TRANSPORTATION', 'Transportation Issues'), ('FAMILY_EMERGENCY', 'Family Emergency'), ('MEDICAL', 'Medical Appointment/Issue'), ('WEATHER', 'Weather Conditions'), ('VEHICLE_BREAKDOWN', 'Vehicle Breakdown'), ('OVERSLEPT', 'Overslept'), ('PERSONAL', 'Personal Reasons'), ('OTHER', 'Other (Specify in notes)')], default='OTHER', max_length=20)),
                ('employee_explanation', models.TextField(blank=True, help_text="Employee's explanation for the delay")),
                ('has_valid_excuse', models.BooleanField(default=False, help_text='Manager determined excuse is valid')),
                ('supporting_document', models.FileField(blank=True, help_text='Supporting document (medical cert, accident report, etc.)', null=True, upload_to='hr/delay_documents/%Y/%m/')),
                ('severity', models.CharField(choices=[('MINOR', 'Minor Delay'), ('MAJOR', 'Major Delay'), ('SEVERE', 'Severe Delay')], default='MINOR', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('disciplinary_action_taken', models.BooleanField(default=False)),
                ('action_description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_incidents', to='hr.hremployee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_delays', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delay Incident',
                'verbose_name_plural': 'Delay Incidents',
                'db_table': 'hr_delay_incident',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='ix_delay_emp_date'), models.Index(fields=['date', 'severity'], name='ix_delay_date_severity')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
