# Generated by Django 5.2.6 on 2025-11-23 00:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_activitylog_notification"),
        ("hr", "0004_alter_leavepolicy_leave_type_attendanceconfiguration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique asset type code (e.g., LAPTOP, PHONE, VEHICLE)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Asset type name", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Asset type description"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Asset category (IT, Transport, Safety, Tools, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "requires_serial_number",
                    models.BooleanField(
                        default=True,
                        help_text="Does this asset type require serial number tracking?",
                    ),
                ),
                (
                    "requires_maintenance",
                    models.BooleanField(
                        default=False,
                        help_text="Does this asset type require regular maintenance?",
                    ),
                ),
                (
                    "maintenance_interval_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Maintenance interval in days (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "depreciation_period_months",
                    models.IntegerField(
                        blank=True, help_text="Depreciation period in months", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this asset type active?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_asset_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Type",
                "verbose_name_plural": "Asset Types",
                "db_table": "hr_asset_type",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="HRAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(
                        help_text="Unique asset tag/identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Asset name/description", max_length=200
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="Manufacturer serial number",
                        max_length=100,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, help_text="Manufacturer/brand", max_length=100
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, help_text="Model number/name", max_length=100
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Technical specifications (JSON)",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, help_text="Date of purchase", null=True
                    ),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Purchase cost",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, help_text="Supplier/vendor name", max_length=200
                    ),
                ),
                (
                    "warranty_expiry_date",
                    models.DateField(
                        blank=True, help_text="Warranty expiration date", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("assigned", "Assigned"),
                            ("in_maintenance", "In Maintenance"),
                            ("retired", "Retired"),
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                        ],
                        default="available",
                        help_text="Current status",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                            ("retired", "Retired"),
                        ],
                        default="good",
                        help_text="Physical condition",
                        max_length=20,
                    ),
                ),
                (
                    "current_location",
                    models.CharField(
                        blank=True,
                        help_text="Current physical location",
                        max_length=200,
                    ),
                ),
                (
                    "last_maintenance_date",
                    models.DateField(
                        blank=True, help_text="Date of last maintenance", null=True
                    ),
                ),
                (
                    "next_maintenance_date",
                    models.DateField(
                        blank=True,
                        help_text="Next scheduled maintenance date",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.ForeignKey(
                        help_text="Type of asset",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="hr.assettype",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cost center responsible for this asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="core.costcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_hr_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Purchase currency",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "db_table": "hr_asset",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_date",
                    models.DateField(help_text="Date asset was assigned to employee"),
                ),
                (
                    "expected_return_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected return date (for temporary assignments)",
                        null=True,
                    ),
                ),
                (
                    "actual_return_date",
                    models.DateField(
                        blank=True, help_text="Actual return date", null=True
                    ),
                ),
                (
                    "condition_at_assignment",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                            ("retired", "Retired"),
                        ],
                        help_text="Asset condition when assigned",
                        max_length=20,
                    ),
                ),
                (
                    "condition_at_return",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                            ("retired", "Retired"),
                        ],
                        help_text="Asset condition when returned",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("returned", "Returned"),
                            ("lost", "Lost"),
                            ("damaged", "Damaged"),
                        ],
                        default="active",
                        help_text="Assignment status",
                        max_length=20,
                    ),
                ),
                (
                    "assignment_notes",
                    models.TextField(
                        blank=True, help_text="Notes at time of assignment"
                    ),
                ),
                (
                    "return_notes",
                    models.TextField(blank=True, help_text="Notes at time of return"),
                ),
                (
                    "employee_acknowledged",
                    models.BooleanField(
                        default=False,
                        help_text="Employee acknowledged receipt of asset",
                    ),
                ),
                (
                    "acknowledgment_signature",
                    models.TextField(
                        blank=True, help_text="Digital signature or reference"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who assigned the asset",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee receiving the asset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_assignments",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "returned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who processed the return",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asset_returns_processed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        help_text="Asset being assigned",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="hr.hrasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Assignment",
                "verbose_name_plural": "Asset Assignments",
                "db_table": "hr_asset_assignment",
                "ordering": ["-assignment_date"],
            },
        ),
        migrations.CreateModel(
            name="HRContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        help_text="Unique contract reference number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("permanent", "Permanent"),
                            ("temporary", "Temporary"),
                            ("contractor", "Contractor"),
                            ("intern", "Intern"),
                            ("part_time", "Part Time"),
                        ],
                        help_text="Type of employment contract",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(help_text="Contract start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Contract end date (null for permanent contracts)",
                        null=True,
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Basic monthly salary",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "housing_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly housing allowance",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly transport allowance",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "other_allowances",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Other monthly allowances",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True, help_text="Is this the current active contract?"
                    ),
                ),
                (
                    "probation_period_months",
                    models.IntegerField(
                        blank=True, help_text="Probation period in months", null=True
                    ),
                ),
                (
                    "notice_period_days",
                    models.IntegerField(
                        blank=True, help_text="Notice period in days", null=True
                    ),
                ),
                (
                    "work_hours_per_week",
                    models.IntegerField(
                        default=40, help_text="Standard work hours per week"
                    ),
                ),
                (
                    "annual_leave_days",
                    models.IntegerField(
                        default=21, help_text="Annual leave entitlement in days"
                    ),
                ),
                (
                    "contract_file",
                    models.FileField(
                        blank=True,
                        help_text="Scanned contract document",
                        null=True,
                        upload_to="hr/contracts/",
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_hr_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        default="SAR",
                        help_text="Currency for compensation",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.currency",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee associated with this contract",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="hr.hremployee",
                    ),
                ),
            ],
            options={
                "verbose_name": "HR Contract",
                "verbose_name_plural": "HR Contracts",
                "db_table": "hr_contract",
                "ordering": ["-is_current", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="HRShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique shift code (e.g., DAY-01, NIGHT-01)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Shift name (e.g., Day Shift, Night Shift, Morning Shift)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Shift description"),
                ),
                ("start_time", models.TimeField(help_text="Shift start time")),
                ("end_time", models.TimeField(help_text="Shift end time")),
                (
                    "duration_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Shift duration in hours",
                        max_digits=4,
                    ),
                ),
                (
                    "is_night_shift",
                    models.BooleanField(
                        default=False, help_text="Is this a night shift?"
                    ),
                ),
                (
                    "working_days",
                    models.JSONField(
                        default=list,
                        help_text="Days of the week this shift applies to (JSON array of day codes)",
                    ),
                ),
                (
                    "break_duration_minutes",
                    models.IntegerField(
                        default=30, help_text="Break duration in minutes"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this shift template active?"
                    ),
                ),
                (
                    "overtime_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Overtime rate multiplier for this shift",
                        max_digits=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cost center for this shift",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_templates",
                        to="core.costcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shift_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department this shift is for (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shift_templates",
                        to="hr.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Template",
                "verbose_name_plural": "Shift Templates",
                "db_table": "hr_shift_template",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(help_text="Assignment start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Assignment end date (null for ongoing)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this assignment active?"
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Assignment notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shift_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee assigned to this shift",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_assignments",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "shift_template",
                    models.ForeignKey(
                        help_text="Shift template",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="hr.hrshifttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Assignment",
                "verbose_name_plural": "Shift Assignments",
                "db_table": "hr_shift_assignment",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="assettype",
            index=models.Index(fields=["code"], name="hr_asset_ty_code_735be4_idx"),
        ),
        migrations.AddIndex(
            model_name="assettype",
            index=models.Index(
                fields=["category"], name="hr_asset_ty_categor_5e6376_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assettype",
            index=models.Index(
                fields=["is_active"], name="hr_asset_ty_is_acti_3cdc50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrasset",
            index=models.Index(
                fields=["asset_tag"], name="hr_asset_asset_t_2b4e42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrasset",
            index=models.Index(
                fields=["asset_type", "status"], name="hr_asset_asset_t_85d663_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrasset",
            index=models.Index(
                fields=["serial_number"], name="hr_asset_serial__9be7e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrasset",
            index=models.Index(fields=["status"], name="hr_asset_status_3a029b_idx"),
        ),
        migrations.AddIndex(
            model_name="assetassignment",
            index=models.Index(
                fields=["employee", "status"], name="hr_asset_as_employe_589809_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetassignment",
            index=models.Index(
                fields=["asset", "status"], name="hr_asset_as_asset_i_4466f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetassignment",
            index=models.Index(
                fields=["assignment_date"], name="hr_asset_as_assignm_a53b30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetassignment",
            index=models.Index(
                fields=["expected_return_date"], name="hr_asset_as_expecte_8eb6fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrcontract",
            index=models.Index(
                fields=["employee", "is_current"], name="hr_contract_employe_6e0a2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrcontract",
            index=models.Index(
                fields=["contract_type"], name="hr_contract_contrac_35b969_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrcontract",
            index=models.Index(
                fields=["start_date"], name="hr_contract_start_d_941744_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrshifttemplate",
            index=models.Index(fields=["code"], name="hr_shift_te_code_1209d8_idx"),
        ),
        migrations.AddIndex(
            model_name="hrshifttemplate",
            index=models.Index(
                fields=["is_active"], name="hr_shift_te_is_acti_05289b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hrshifttemplate",
            index=models.Index(
                fields=["department"], name="hr_shift_te_departm_b624a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftassignment",
            index=models.Index(
                fields=["employee", "is_active"], name="hr_shift_as_employe_4dde89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftassignment",
            index=models.Index(
                fields=["shift_template"], name="hr_shift_as_shift_t_bc596d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shiftassignment",
            index=models.Index(
                fields=["start_date", "end_date"], name="hr_shift_as_start_d_ddda93_idx"
            ),
        ),
    ]
