# Generated by Django 5.2.6 on 2025-11-21 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NCRFinancialImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('ncr_number', models.CharField(db_index=True, help_text='NCR number reference (e.g., NCR-2025-0001)', max_length=50, unique=True)),
                ('estimated_cost_impact', models.DecimalField(decimal_places=2, default=0, help_text='Estimated cost of the nonconformance', max_digits=12)),
                ('actual_cost_impact', models.DecimalField(decimal_places=2, default=0, help_text='Actual cost after resolution', max_digits=12)),
                ('lost_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Lost revenue due to this NCR', max_digits=12)),
                ('notes', models.TextField(blank=True, default='', help_text='Financial impact notes and breakdown')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NCR Financial Impact',
                'verbose_name_plural': 'NCR Financial Impacts',
                'db_table': 'finance_ncr_financial_impact',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ncr_number'], name='ix_fin_ncr_number'), models.Index(fields=['created_at'], name='ix_fin_ncr_created')],
            },
        ),
    ]
