# Generated by Django 5.2.6 on 2025-11-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitdesignrevision',
            name='erp_bom_number',
            field=models.CharField(blank=True, help_text='ERP BOM Number', max_length=50),
        ),
        migrations.AddField(
            model_name='bitdesignrevision',
            name='erp_item_number',
            field=models.CharField(blank=True, help_text='ERP Item/Material Code', max_length=50),
        ),
        migrations.AddField(
            model_name='bitdesignrevision',
            name='last_purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last purchase cost', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bitdesignrevision',
            name='standard_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Standard cost per unit', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='erp_bom_number',
            field=models.CharField(blank=True, help_text='ERP BOM Number', max_length=50),
        ),
    ]
