# Generated by Django 5.2.6 on 2025-11-18 22:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluation", "0003_alter_requirementinstance_waived_by"),
        ("hr", "0003_remove_hremployee_report_to_department_cost_center_and_more"),
        ("inventory", "0002_bitdesignrevision_erp_bom_number_and_more"),
        ("production", "0002_jobcard_cost_center_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CutterOwnershipCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Category code (e.g., ENO_AS_NEW, ENO_GROUND)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name (e.g., 'ENO As New Cutter')",
                        max_length=100,
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Abbreviated name for column headers (e.g., 'ENO As New')",
                        max_length=30,
                    ),
                ),
                (
                    "consumption_priority",
                    models.IntegerField(
                        default=50, help_text="Lower priority consumed first (1-99)"
                    ),
                ),
                (
                    "is_new_stock",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is brand new purchased stock",
                    ),
                ),
                (
                    "is_reclaimed",
                    models.BooleanField(
                        default=False, help_text="True if reclaimed from used bits"
                    ),
                ),
                (
                    "is_ground",
                    models.BooleanField(
                        default=False, help_text="True if cutters have been reground"
                    ),
                ),
                (
                    "excel_column_label",
                    models.CharField(
                        blank=True,
                        help_text="Excel sheet column label for reference (e.g., 'ENO As New Cutter')",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Cutter Ownership Category",
                "verbose_name_plural": "Cutter Ownership Categories",
                "db_table": "inventory_cutter_ownership_category",
                "ordering": ["sort_order", "consumption_priority"],
            },
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="quantity_in",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Quantity added to ownership category (for cutters)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="quantity_out",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Quantity removed from ownership category (for cutters)",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="from_ownership",
            field=models.ForeignKey(
                blank=True,
                help_text="Source ownership (generic)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions_from",
                to="inventory.ownershiptype",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="to_ownership",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination ownership (generic)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions_to",
                to="inventory.ownershiptype",
            ),
        ),
        migrations.CreateModel(
            name="CutterBOMGridHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "blade_count",
                    models.PositiveIntegerField(
                        help_text="Number of blades on this bit"
                    ),
                ),
                (
                    "max_pockets_per_blade",
                    models.PositiveIntegerField(
                        help_text="Maximum pockets in any blade"
                    ),
                ),
                (
                    "cutter_ordering_scheme",
                    models.CharField(
                        choices=[
                            ("CONTINUOUS", "Continuous (1 to N across all blades)"),
                            ("RESET_PER_TYPE", "Reset per Primary/Secondary"),
                            ("FORMATION", "Formation Engagement Order (apex to gauge)"),
                        ],
                        default="CONTINUOUS",
                        help_text="How to number cutters in the grid",
                        max_length=20,
                    ),
                ),
                (
                    "total_primary_cutters",
                    models.PositiveIntegerField(
                        default=0, help_text="Total primary cutters in grid"
                    ),
                ),
                (
                    "total_secondary_cutters",
                    models.PositiveIntegerField(
                        default=0, help_text="Total secondary cutters in grid"
                    ),
                ),
                (
                    "show_reclaimed_cutters",
                    models.BooleanField(
                        default=False,
                        help_text="Show reclaimed cutters in availability (typically False for new bits)",
                    ),
                ),
                (
                    "bom_header",
                    models.OneToOneField(
                        help_text="Parent BOM header",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutter_grid",
                        to="inventory.bomheader",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutter BOM Grid Header",
                "verbose_name_plural": "Cutter BOM Grid Headers",
                "db_table": "inventory_cutter_bom_grid_header",
            },
        ),
        migrations.CreateModel(
            name="CutterDetail",
            fields=[
                (
                    "item",
                    models.OneToOneField(
                        help_text="Link to parent Item record",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="cutter_detail",
                        serialize=False,
                        to="inventory.item",
                    ),
                ),
                (
                    "sap_number",
                    models.CharField(
                        db_index=True,
                        help_text="SAP/ERP material number (e.g., 802065, 179692)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "cutter_type",
                    models.CharField(
                        db_index=True,
                        help_text="Cutter type: Round, IA-STL, Shyfter, Short Bullet, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "cutter_size",
                    models.CharField(
                        db_index=True,
                        help_text="Cutter size: 1313, 1308, 13MM Long, 1613, 19MM, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        db_index=True,
                        help_text="Cutter grade: CT97, ELITE RC, M1, CT62, CT36, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "chamfer",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Chamfer size: 0.010", 0.018", 0.012R, etc.',
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("P", "P-Premium"),
                            ("S", "S-Super Premium"),
                            ("B", "B-Standard"),
                            ("O", "O-Other"),
                            ("D", "D-Depth of Cut"),
                        ],
                        db_index=True,
                        help_text="Cutter category classification",
                        max_length=1,
                    ),
                ),
                (
                    "more_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional description from Excel",
                    ),
                ),
                (
                    "is_obsolete",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if cutter is obsolete (see replacement_cutter)",
                    ),
                ),
                (
                    "replacement_cutter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Replacement cutter if this one is obsolete",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces_cutters",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutter Detail",
                "verbose_name_plural": "Cutter Details",
                "db_table": "inventory_cutter_detail",
                "ordering": ["sap_number"],
            },
        ),
        migrations.CreateModel(
            name="CutterBOMSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Total required quantity in BOM"
                    ),
                ),
                (
                    "primary_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Count as primary cutters"
                    ),
                ),
                (
                    "secondary_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Count as secondary cutters"
                    ),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "grid_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="inventory.cutterbomgridheader",
                    ),
                ),
                (
                    "cutter_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_summaries",
                        to="inventory.cutterdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutter BOM Summary",
                "verbose_name_plural": "Cutter BOM Summaries",
                "db_table": "inventory_cutter_bom_summary",
            },
        ),
        migrations.CreateModel(
            name="CutterBOMGridCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "blade_number",
                    models.PositiveIntegerField(help_text="Blade number (1-based)"),
                ),
                (
                    "pocket_number",
                    models.PositiveIntegerField(
                        help_text="Pocket number within blade (1-based)"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True,
                        help_text="Primary cutter (True) or Secondary/backup cutter (False)",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True,
                        help_text="Location name (e.g., 'Cone 1', 'Nose 2', 'Gauge 3')",
                        max_length=50,
                    ),
                ),
                (
                    "cutter_sequence",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Sequence number based on ordering scheme",
                        null=True,
                    ),
                ),
                (
                    "formation_order",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Formation engagement order (for FORMATION ordering scheme)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Design notes for this position"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bit section (Cone, Nose, Taper, Shoulder, Gauge)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="evaluation.bitsection",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grid_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="inventory.cutterbomgridheader",
                    ),
                ),
                (
                    "cutter_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Required cutter type for this position",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_cells",
                        to="inventory.cutterdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutter BOM Grid Cell",
                "verbose_name_plural": "Cutter BOM Grid Cells",
                "db_table": "inventory_cutter_bom_grid_cell",
                "ordering": ["blade_number", "-is_primary", "pocket_number"],
            },
        ),
        migrations.CreateModel(
            name="CutterMapHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "map_type",
                    models.CharField(
                        choices=[
                            ("DESIGN", "Design Map (from BOM)"),
                            ("AS_RECEIVED", "As Received (incoming inspection)"),
                            ("AS_BUILT", "As Built (production)"),
                            ("POST_EVAL", "Post Evaluation (after QC)"),
                            ("POST_NDT", "Post NDT Inspection"),
                            ("POST_REWORK", "Post Rework"),
                            ("FINAL", "Final (before shipping)"),
                        ],
                        help_text="Stage this map represents",
                        max_length=20,
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        default=1, help_text="Sequence number for multiple reworks"
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False, help_text="All cells filled"),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALID", "Valid (matches BOM)"),
                            ("HAS_SUBSTITUTIONS", "Has Substitutions"),
                            ("INCOMPLETE", "Incomplete"),
                            ("HAS_ERRORS", "Has Errors"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("validation_notes", models.TextField(blank=True)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_cutter_maps",
                        to="hr.hremployee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cutter_maps",
                        to="production.jobcard",
                    ),
                ),
                (
                    "source_bom_grid",
                    models.ForeignKey(
                        help_text="BOM grid this map is based on",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maps",
                        to="inventory.cutterbomgridheader",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutter Map Header",
                "verbose_name_plural": "Cutter Map Headers",
                "db_table": "inventory_cutter_map_header",
                "ordering": ["job_card", "map_type", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="CutterMapCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                ("blade_number", models.PositiveIntegerField()),
                ("pocket_number", models.PositiveIntegerField()),
                ("is_primary", models.BooleanField(default=True)),
                ("location_name", models.CharField(blank=True, max_length=50)),
                ("cutter_sequence", models.PositiveIntegerField(blank=True, null=True)),
                ("formation_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EMPTY", "Empty"),
                            ("CORRECT", "Correct (matches BOM)"),
                            ("SUBSTITUTED", "Substituted (different type)"),
                            ("DAMAGED", "Damaged"),
                            ("REWORKED", "Reworked"),
                            ("REPLACED", "Replaced"),
                            ("PENDING", "Pending"),
                        ],
                        default="EMPTY",
                        max_length=20,
                    ),
                ),
                (
                    "technical_notes",
                    models.TextField(blank=True, help_text="Technical/design notes"),
                ),
                (
                    "receiving_notes",
                    models.TextField(blank=True, help_text="Receiving inspector notes"),
                ),
                (
                    "production_notes",
                    models.TextField(blank=True, help_text="Production team notes"),
                ),
                (
                    "qc_notes",
                    models.TextField(blank=True, help_text="QC evaluation notes"),
                ),
                (
                    "ndt_notes",
                    models.TextField(blank=True, help_text="NDT inspection notes"),
                ),
                (
                    "rework_notes",
                    models.TextField(blank=True, help_text="Rework notes"),
                ),
                (
                    "final_inspection_notes",
                    models.TextField(blank=True, help_text="Final inspector notes"),
                ),
                (
                    "actual_cutter_serial",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific serial number installed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="map_cells",
                        to="inventory.serialunit",
                    ),
                ),
                (
                    "actual_cutter_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="What is actually installed",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="map_cells_actual",
                        to="inventory.cutterdetail",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "required_cutter_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="What should be installed (from BOM)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="map_cells_required",
                        to="inventory.cutterdetail",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="evaluation.bitsection",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "map_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="inventory.cuttermapheader",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutter Map Cell",
                "verbose_name_plural": "Cutter Map Cells",
                "db_table": "inventory_cutter_map_cell",
                "ordering": ["blade_number", "-is_primary", "pocket_number"],
            },
        ),
        migrations.CreateModel(
            name="CutterInventorySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current stock quantity",
                        max_digits=12,
                    ),
                ),
                (
                    "consumption_6month",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total consumed in last 6 months (182 days)",
                        max_digits=12,
                    ),
                ),
                (
                    "consumption_3month",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total consumed in last 3 months (91 days)",
                        max_digits=12,
                    ),
                ),
                (
                    "consumption_2month",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Estimated 2-month consumption (6mo / 3, rounded up)",
                        max_digits=12,
                    ),
                ),
                (
                    "safety_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tiered safety buffer based on consumption",
                        max_digits=12,
                    ),
                ),
                (
                    "bom_requirement",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total quantity needed for bits in production",
                        max_digits=12,
                    ),
                ),
                (
                    "on_order",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total quantity on open purchase orders",
                        max_digits=12,
                    ),
                ),
                (
                    "forecast",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Projected balance: current - BOM + on_order",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "OK - Stock Adequate"),
                            ("LOW", "Low - Below Safety Stock"),
                            ("SHORTAGE", "Shortage - Below BOM Requirement"),
                            ("EXCESS", "Excess - High Inventory"),
                        ],
                        default="OK",
                        max_length=10,
                    ),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_summaries",
                        to="inventory.item",
                    ),
                ),
                (
                    "ownership_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_summaries",
                        to="inventory.cutterownershipcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutter Inventory Summary",
                "verbose_name_plural": "Cutter Inventory Summaries",
                "db_table": "inventory_cutter_summary",
                "ordering": ["item__sku", "ownership_category__consumption_priority"],
            },
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="cutter_ownership_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Cutter ownership category (for cutter items only)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="inventory.cutterownershipcategory",
            ),
        ),
        migrations.CreateModel(
            name="CutterPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "effective_date",
                    models.DateField(
                        db_index=True,
                        help_text="Date when this price becomes effective",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Price per unit in specified currency",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="SAR",
                        help_text="Currency code (ISO 4217)",
                        max_length=3,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("PO", "Purchase Order"),
                            ("MANUAL", "Manual Adjustment"),
                            ("IMPORT", "Excel Import"),
                            ("CONTRACT", "Contract Agreement"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="PO number, contract reference, etc.",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="Cutter item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cutter Price History",
                "verbose_name_plural": "Cutter Price Histories",
                "db_table": "inventory_cutter_price_history",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="BOMUsageTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "was_modified",
                    models.BooleanField(
                        default=False,
                        help_text="Was BOM modified for this job (e.g., shortage handling, testing)",
                    ),
                ),
                (
                    "modification_notes",
                    models.TextField(blank=True, help_text="Why BOM was modified"),
                ),
                (
                    "modified_cells",
                    models.JSONField(
                        blank=True,
                        help_text="Record of which cells were modified",
                        null=True,
                    ),
                ),
                (
                    "bom_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_records",
                        to="inventory.bomheader",
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_usage",
                        to="production.jobcard",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bom_usage_records",
                        to="hr.hremployee",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM Usage Record",
                "verbose_name_plural": "BOM Usage Records",
                "db_table": "inventory_bom_usage_tracking",
                "ordering": ["-used_at"],
                "indexes": [
                    models.Index(
                        fields=["bom_header", "used_at"],
                        name="inventory_b_bom_hea_2cdfd1_idx",
                    ),
                    models.Index(
                        fields=["job_card"], name="inventory_b_job_car_63b373_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cutterbomgridheader",
            index=models.Index(
                fields=["bom_header"], name="inventory_c_bom_hea_d5f0ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cutterdetail",
            index=models.Index(fields=["sap_number"], name="ix_cd_sap_number"),
        ),
        migrations.AddIndex(
            model_name="cutterdetail",
            index=models.Index(
                fields=["cutter_type", "cutter_size"], name="ix_cd_type_size"
            ),
        ),
        migrations.AddIndex(
            model_name="cutterdetail",
            index=models.Index(
                fields=["category", "is_obsolete"], name="ix_cd_cat_obs"
            ),
        ),
        migrations.AddIndex(
            model_name="cutterbomsummary",
            index=models.Index(
                fields=["grid_header", "cutter_type"],
                name="inventory_c_grid_he_410bb0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cutterbomsummary",
            unique_together={("grid_header", "cutter_type")},
        ),
        migrations.AddIndex(
            model_name="cutterbomgridcell",
            index=models.Index(
                fields=["grid_header", "blade_number"],
                name="inventory_c_grid_he_35beb8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cutterbomgridcell",
            index=models.Index(
                fields=["grid_header", "cutter_type"],
                name="inventory_c_grid_he_d6e6c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cutterbomgridcell",
            index=models.Index(
                fields=["cutter_sequence"], name="inventory_c_cutter__a20540_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cutterbomgridcell",
            unique_together={
                ("grid_header", "blade_number", "pocket_number", "is_primary")
            },
        ),
        migrations.AddIndex(
            model_name="cuttermapheader",
            index=models.Index(
                fields=["job_card", "map_type"], name="inventory_c_job_car_ab65ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuttermapheader",
            index=models.Index(
                fields=["source_bom_grid"], name="inventory_c_source__3b6e2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuttermapheader",
            index=models.Index(
                fields=["validation_status"], name="inventory_c_validat_07ebe5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cuttermapheader",
            unique_together={("job_card", "map_type", "sequence_number")},
        ),
        migrations.AddIndex(
            model_name="cuttermapcell",
            index=models.Index(
                fields=["map_header", "blade_number"],
                name="inventory_c_map_hea_56fc83_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cuttermapcell",
            index=models.Index(
                fields=["map_header", "status"], name="inventory_c_map_hea_03db8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuttermapcell",
            index=models.Index(
                fields=["actual_cutter_type"], name="inventory_c_actual__8ba6a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cuttermapcell",
            index=models.Index(
                fields=["actual_cutter_serial"], name="inventory_c_actual__81bb7c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cuttermapcell",
            unique_together={
                ("map_header", "blade_number", "pocket_number", "is_primary")
            },
        ),
        migrations.AddIndex(
            model_name="cutterinventorysummary",
            index=models.Index(
                fields=["item", "ownership_category"], name="ix_cis_item_cat"
            ),
        ),
        migrations.AddIndex(
            model_name="cutterinventorysummary",
            index=models.Index(fields=["status"], name="ix_cis_status"),
        ),
        migrations.AlterUniqueTogether(
            name="cutterinventorysummary",
            unique_together={("item", "ownership_category")},
        ),
        migrations.AddIndex(
            model_name="cutterpricehistory",
            index=models.Index(
                fields=["item", "-effective_date"], name="ix_cph_item_date"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cutterpricehistory",
            unique_together={("item", "effective_date")},
        ),
    ]
