# Generated by Django 5.2.6 on 2025-11-19 04:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_cutterownershipcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RollerConeBearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Bearing code', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('bearing_type', models.CharField(choices=[('OPEN_ROLLER', 'Open Roller Bearing'), ('SEALED_ROLLER', 'Sealed Roller Bearing'), ('JOURNAL', 'Journal Bearing'), ('SEALED_JOURNAL', 'Sealed Journal Bearing'), ('BALL', 'Ball Bearing')], max_length=50)),
                ('is_sealed', models.BooleanField(default=False, help_text='Whether bearing has seal system')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Roller Cone Bearing Type',
                'verbose_name_plural': 'Roller Cone Bearing Types',
                'db_table': 'inventory_roller_cone_bearing',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RollerConeBitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iadc_code', models.CharField(db_index=True, help_text='IADC classification code (e.g., 111, 437, 537, 617)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Descriptive name', max_length=200)),
                ('formation_type', models.CharField(help_text='Formation type description (e.g., Soft, Medium, Hard)', max_length=100)),
                ('series', models.CharField(help_text='Series number (1-8)', max_length=10)),
                ('tooth_type', models.CharField(choices=[('MILLED', 'Milled Steel Tooth'), ('INSERT', 'Tungsten Carbide Insert')], help_text='Type of cutting structure', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Roller Cone Bit Type',
                'verbose_name_plural': 'Roller Cone Bit Types',
                'db_table': 'inventory_roller_cone_bit_type',
                'ordering': ['series', 'iadc_code'],
            },
        ),
        migrations.CreateModel(
            name='RollerConeSeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('seal_type', models.CharField(choices=[('METAL_FACE', 'Metal Face Seal'), ('O_RING', 'O-Ring Seal'), ('HYBRID', 'Hybrid Seal System'), ('NONE', 'No Seal (Open Bearing)')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Roller Cone Seal Type',
                'verbose_name_plural': 'Roller Cone Seal Types',
                'db_table': 'inventory_roller_cone_seal',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bitdesign',
            name='bit_category',
            field=models.CharField(choices=[('PDC', 'PDC (Polycrystalline Diamond Compact)'), ('ROLLER_CONE', 'Roller Cone (Tricone/Bicone)')], db_index=True, default='PDC', help_text='Type of bit technology (PDC or Roller Cone)', max_length=20),
        ),
        migrations.CreateModel(
            name='RollerConeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('part_number', models.CharField(db_index=True, help_text='Manufacturer part number', max_length=100, unique=True)),
                ('component_type', models.CharField(choices=[('CONE', 'Cone Assembly'), ('BEARING_KIT', 'Bearing Kit'), ('SEAL_KIT', 'Seal Kit'), ('INSERT', 'Tungsten Carbide Insert'), ('NOZZLE', 'Nozzle'), ('SHANK', 'Bit Shank/Body'), ('LOCKING', 'Locking Element (Ball/Snapring)'), ('HARDFACING', 'Hardfacing Material'), ('OTHER', 'Other Component')], db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('manufacturer', models.CharField(blank=True, default='', help_text='Component manufacturer', max_length=100)),
                ('oem_part_number', models.CharField(blank=True, default='', help_text='OEM/original part number if aftermarket', max_length=100)),
                ('specifications', models.JSONField(default=dict, help_text='Component-specific specifications (size, material, etc.)')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inventory_item_id', models.BigIntegerField(blank=True, db_index=True, help_text='Reference to inventory.Item if stocked', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roller Cone Component',
                'verbose_name_plural': 'Roller Cone Components',
                'db_table': 'inventory_roller_cone_component',
                'ordering': ['component_type', 'part_number'],
            },
        ),
        migrations.CreateModel(
            name='RollerConeBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity per bit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.CharField(blank=True, default='', help_text='Position or location of component in assembly', max_length=100)),
                ('is_optional', models.BooleanField(default=False, help_text='Whether this component is optional')),
                ('notes', models.TextField(blank=True, default='')),
                ('bit_design_revision', models.ForeignKey(help_text='MAT number this BOM applies to', on_delete=django.db.models.deletion.CASCADE, related_name='roller_cone_bom_lines', to='inventory.bitdesignrevision')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('alternate_component', models.ForeignKey(blank=True, help_text='Alternate/substitute component', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_for', to='inventory.rollerconecomponent')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_usages', to='inventory.rollerconecomponent')),
            ],
            options={
                'verbose_name': 'Roller Cone BOM Line',
                'verbose_name_plural': 'Roller Cone BOM Lines',
                'db_table': 'inventory_roller_cone_bom',
                'ordering': ['bit_design_revision', 'component__component_type', 'position'],
            },
        ),
        migrations.CreateModel(
            name='RollerConeDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('number_of_cones', models.IntegerField(default=3, help_text='Number of cones (typically 3 for tricone, 2 for bicone)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('tooth_structure', models.CharField(choices=[('MILLED', 'Milled Steel Tooth'), ('INSERT', 'Tungsten Carbide Insert'), ('HYBRID', 'Hybrid (Mixed)')], help_text='Type of cutting elements on cones', max_length=50)),
                ('insert_type', models.CharField(blank=True, default='', help_text='Type of inserts if insert bit (e.g., Chisel, Conical, Wedge)', max_length=100)),
                ('insert_size_range', models.CharField(blank=True, default='', help_text='Size range of inserts', max_length=100)),
                ('total_insert_count', models.IntegerField(blank=True, help_text='Total number of inserts per bit', null=True)),
                ('nozzle_count', models.IntegerField(blank=True, help_text='Number of nozzle ports', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('nozzle_configuration', models.CharField(blank=True, default='', help_text='Standard nozzle setup (e.g., 3x12, 4x14)', max_length=100)),
                ('journal_angle_1', models.DecimalField(blank=True, decimal_places=2, help_text='Journal angle for cone 1 (degrees)', max_digits=5, null=True)),
                ('journal_angle_2', models.DecimalField(blank=True, decimal_places=2, help_text='Journal angle for cone 2 (degrees)', max_digits=5, null=True)),
                ('journal_angle_3', models.DecimalField(blank=True, decimal_places=2, help_text='Journal angle for cone 3 (degrees)', max_digits=5, null=True)),
                ('cone_offset_inches', models.DecimalField(blank=True, decimal_places=3, help_text='Cone offset from center (inches)', max_digits=5, null=True)),
                ('gage_protection', models.CharField(blank=True, default='', help_text='Gage protection features (hardfacing, inserts, etc.)', max_length=100)),
                ('jet_velocity_optimized', models.BooleanField(default=False, help_text='Whether bit is optimized for jet velocity')),
                ('extended_nozzles', models.BooleanField(default=False, help_text='Whether bit has extended nozzles')),
                ('recommended_rpm_min', models.IntegerField(blank=True, help_text='Minimum recommended RPM', null=True)),
                ('recommended_rpm_max', models.IntegerField(blank=True, help_text='Maximum recommended RPM', null=True)),
                ('recommended_wob_min_klbs', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum recommended weight on bit (1000 lbs)', max_digits=6, null=True)),
                ('recommended_wob_max_klbs', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum recommended weight on bit (1000 lbs)', max_digits=6, null=True)),
                ('recommended_formations', models.TextField(blank=True, default='', help_text='Recommended formation types and drilling conditions')),
                ('special_features', models.TextField(blank=True, default='', help_text='Special features or design innovations')),
                ('notes', models.TextField(blank=True, default='')),
                ('bearing_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='inventory.rollerconebearing')),
                ('bit_design', models.OneToOneField(help_text='Parent bit design (must be roller cone type)', on_delete=django.db.models.deletion.CASCADE, related_name='roller_cone_design', to='inventory.bitdesign')),
                ('bit_type', models.ForeignKey(help_text='IADC bit type classification', on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='inventory.rollerconebittype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('seal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='inventory.rollerconeseal')),
            ],
            options={
                'verbose_name': 'Roller Cone Design',
                'verbose_name_plural': 'Roller Cone Designs',
                'db_table': 'inventory_roller_cone_design',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rollerconecomponent',
            index=models.Index(fields=['component_type', 'is_active'], name='ix_rc_comp_type'),
        ),
        migrations.AddIndex(
            model_name='rollerconecomponent',
            index=models.Index(fields=['part_number'], name='ix_rc_comp_part'),
        ),
        migrations.AlterUniqueTogether(
            name='rollerconebom',
            unique_together={('bit_design_revision', 'component', 'position')},
        ),
    ]
