# Generated by Django 5.2.6 on 2025-11-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rollerconebearing_rollerconebittype_rollerconeseal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitdesign',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bitdesign',
            name='level',
        ),
        migrations.RemoveField(
            model_name='bitdesign',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='bitdesignrevision',
            name='bit_design',
        ),
        migrations.RemoveField(
            model_name='rollerconedesign',
            name='bit_design',
        ),
        migrations.RemoveField(
            model_name='bitdesignrevision',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bitdesignrevision',
            name='design_type',
        ),
        migrations.RemoveField(
            model_name='bitdesignrevision',
            name='superseded_by',
        ),
        migrations.RemoveField(
            model_name='bitdesignrevision',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='source_mat',
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='target_mat',
        ),
        migrations.AlterField(
            model_name='serialunitmathistory',
            name='old_mat',
            field=models.ForeignKey(blank=True, help_text='Previous MAT revision (null if first assignment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_as_old', to='engineering.bitdesignrevision'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='from_mat',
            field=models.ForeignKey(blank=True, help_text='Source MAT (for retrofit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_from_mat', to='engineering.bitdesignrevision'),
        ),
        migrations.AlterField(
            model_name='serialunit',
            name='current_mat',
            field=models.ForeignKey(blank=True, help_text='Current MAT revision (may differ from Item after retrofit)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serial_units', to='engineering.bitdesignrevision'),
        ),
        migrations.RemoveField(
            model_name='rollerconebom',
            name='bit_design_revision',
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='to_mat',
            field=models.ForeignKey(blank=True, help_text='Target MAT (for retrofit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_to_mat', to='engineering.bitdesignrevision'),
        ),
        migrations.AlterField(
            model_name='serialunitmathistory',
            name='new_mat',
            field=models.ForeignKey(help_text='New MAT revision', on_delete=django.db.models.deletion.PROTECT, related_name='history_as_new', to='engineering.bitdesignrevision'),
        ),
        migrations.AlterField(
            model_name='item',
            name='bit_design_revision',
            field=models.ForeignKey(blank=True, help_text='For bit-related items: the specific MAT/design revision', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='engineering.bitdesignrevision'),
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='superseded_by',
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='bomline',
            name='bom_header',
        ),
        migrations.AlterField(
            model_name='cutterbomgridheader',
            name='bom_header',
            field=models.OneToOneField(help_text='Parent BOM header', on_delete=django.db.models.deletion.CASCADE, related_name='cutter_grid', to='engineering.bomheader'),
        ),
        migrations.AlterField(
            model_name='bomusagetracking',
            name='bom_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='engineering.bomheader'),
        ),
        migrations.RemoveField(
            model_name='bomline',
            name='component_item',
        ),
        migrations.RemoveField(
            model_name='bomline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bomline',
            name='required_condition',
        ),
        migrations.RemoveField(
            model_name='bomline',
            name='required_ownership',
        ),
        migrations.RemoveField(
            model_name='bomline',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='bomline',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='rollerconedesign',
            name='bearing_type',
        ),
        migrations.RemoveField(
            model_name='rollerconedesign',
            name='bit_type',
        ),
        migrations.AlterUniqueTogether(
            name='rollerconebom',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rollerconebom',
            name='alternate_component',
        ),
        migrations.RemoveField(
            model_name='rollerconebom',
            name='component',
        ),
        migrations.RemoveField(
            model_name='rollerconebom',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rollerconebom',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='rollerconecomponent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rollerconecomponent',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='rollerconedesign',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rollerconedesign',
            name='seal_type',
        ),
        migrations.RemoveField(
            model_name='rollerconedesign',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='min_stock_qty',
        ),
        migrations.AlterField(
            model_name='item',
            name='reorder_point',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity at which to reorder (trigger point for new purchase/production order)', max_digits=10),
        ),
        migrations.DeleteModel(
            name='BitDesignLevel',
        ),
        migrations.DeleteModel(
            name='BitDesign',
        ),
        migrations.DeleteModel(
            name='BitDesignType',
        ),
    ]
