# Generated by Django 5.2.6 on 2025-11-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0004_alter_evaluationsession_mat_revision'),
        ('inventory', '0005_remove_bitdesign_created_by_remove_bitdesign_level_and_more'),
        ('production', '0004_alter_cutterlayout_design_revision_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitDesignRevision',
        ),
        migrations.DeleteModel(
            name='BOMHeader',
        ),
        migrations.DeleteModel(
            name='BOMLine',
        ),
        migrations.DeleteModel(
            name='RollerConeBearing',
        ),
        migrations.DeleteModel(
            name='RollerConeBitType',
        ),
        migrations.DeleteModel(
            name='RollerConeBOM',
        ),
        migrations.DeleteModel(
            name='RollerConeComponent',
        ),
        migrations.DeleteModel(
            name='RollerConeSeal',
        ),
        migrations.DeleteModel(
            name='RollerConeDesign',
        ),
    ]
