# Generated by Django 5.2.6 on 2025-11-21 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_leavepolicy_leave_type_attendanceconfiguration_and_more'),
        ('knowledge', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateTimeField()),
                ('reading_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Meter Reading',
                'verbose_name_plural': 'Meter Readings',
                'ordering': ['-reading_date'],
            },
        ),
        migrations.CreateModel(
            name='LostSalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('order_reference', models.CharField(max_length=100)),
                ('original_order_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenue_lost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue_delayed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recovery_possible', models.BooleanField(default=True, help_text='Can revenue be recovered later?')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lost Sales Record',
                'verbose_name_plural': 'Lost Sales Records',
                'ordering': ['-confirmed_at'],
                'permissions': [('can_confirm_lost_sales', 'Can confirm lost sales records')],
            },
        ),
        migrations.CreateModel(
            name='PMTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('code', models.CharField(help_text='Template code, e.g., PM-GRN-001', max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructions', models.TextField(help_text='Step-by-step instructions')),
                ('safety_notes', models.TextField(blank=True, help_text='Safety warnings and precautions')),
                ('tools_required', models.TextField(blank=True)),
                ('parts_typically_needed', models.TextField(blank=True)),
                ('frequency_type', models.CharField(choices=[('TIME_BASED', 'Time-Based (days/weeks/months)'), ('METER_BASED', 'Meter-Based (hours/cycles)'), ('CONDITION_BASED', 'Condition-Based')], default='TIME_BASED', max_length=20)),
                ('frequency_days', models.PositiveIntegerField(blank=True, help_text='Interval in days for time-based PM', null=True)),
                ('frequency_hours', models.PositiveIntegerField(blank=True, help_text='Interval in hours for meter-based PM', null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60)),
                ('technicians_required', models.PositiveIntegerField(default=1)),
                ('skill_level_required', models.CharField(choices=[('BASIC', 'Basic - Any Operator'), ('INTERMEDIATE', 'Intermediate - Trained Technician'), ('ADVANCED', 'Advanced - Specialist'), ('EXPERT', 'Expert - Certified Professional')], default='INTERMEDIATE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_shutdown', models.BooleanField(default=False, help_text='Asset must be shut down')),
                ('generates_work_order', models.BooleanField(default=True, help_text='Auto-create work order when due')),
            ],
            options={
                'verbose_name': 'PM Template',
                'verbose_name_plural': 'PM Templates',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('PROGRESS', 'Progress Update'), ('ISSUE', 'Issue Encountered'), ('RESOLUTION', 'Resolution'), ('GENERAL', 'General Note'), ('PARTS', 'Parts Related')], default='GENERAL', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Work Order Note',
                'verbose_name_plural': 'Work Order Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100)),
                ('part_description', models.CharField(max_length=255)),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('warehouse_location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('inventory_item_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('inventory_transaction_id', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Work Order Part',
                'verbose_name_plural': 'Work Order Parts',
            },
        ),
        migrations.RemoveField(
            model_name='lostsales',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='lostsales',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='lostsales',
            name='downtime_event',
        ),
        migrations.RemoveField(
            model_name='lostsales',
            name='production_impact',
        ),
        migrations.RemoveField(
            model_name='lostsales',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='pmplan',
            name='applies_to_category',
        ),
        migrations.RemoveField(
            model_name='pmplan',
            name='applies_to_specific_assets',
        ),
        migrations.RemoveField(
            model_name='pmplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pmplan',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['asset_code'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ['name'], 'verbose_name': 'Asset Category', 'verbose_name_plural': 'Asset Categories'},
        ),
        migrations.AlterModelOptions(
            name='assetdocument',
            options={'verbose_name': 'Asset Document', 'verbose_name_plural': 'Asset Documents'},
        ),
        migrations.AlterModelOptions(
            name='assetlocation',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Asset Location', 'verbose_name_plural': 'Asset Locations'},
        ),
        migrations.AlterModelOptions(
            name='downtimeevent',
            options={'ordering': ['-start_time'], 'permissions': [('can_record_downtime', 'Can record downtime events')], 'verbose_name': 'Downtime Event', 'verbose_name_plural': 'Downtime Events'},
        ),
        migrations.AlterModelOptions(
            name='pmtask',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'PM Task', 'verbose_name_plural': 'PM Tasks'},
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='ix_maint_asset_cat_loc',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='ix_maint_asset_critical',
        ),
        migrations.RemoveIndex(
            model_name='asset',
            name='ix_maint_asset_next_pm',
        ),
        migrations.RemoveIndex(
            model_name='assetcategory',
            name='ix_maint_cat_code',
        ),
        migrations.RemoveIndex(
            model_name='assetcategory',
            name='ix_maint_cat_parent',
        ),
        migrations.RemoveIndex(
            model_name='assetdocument',
            name='ix_maint_doc_asset_type',
        ),
        migrations.RemoveIndex(
            model_name='assetdocument',
            name='ix_maint_doc_current',
        ),
        migrations.RemoveIndex(
            model_name='assetlocation',
            name='ix_maint_loc_code',
        ),
        migrations.RemoveIndex(
            model_name='assetlocation',
            name='ix_maint_loc_parent',
        ),
        migrations.RemoveIndex(
            model_name='assetlocation',
            name='ix_maint_loc_active',
        ),
        migrations.RemoveIndex(
            model_name='downtimeevent',
            name='ix_maint_dt_type_reason',
        ),
        migrations.RemoveIndex(
            model_name='downtimeevent',
            name='ix_maint_dt_times',
        ),
        migrations.RemoveIndex(
            model_name='downtimeevent',
            name='ix_maint_dt_prod_aff',
        ),
        migrations.RemoveIndex(
            model_name='downtimeevent',
            name='ix_maint_dt_verified',
        ),
        migrations.RemoveIndex(
            model_name='pmschedule',
            name='ix_maint_pmsched_due',
        ),
        migrations.RemoveIndex(
            model_name='pmschedule',
            name='ix_maint_pmsched_asset',
        ),
        migrations.RemoveIndex(
            model_name='pmschedule',
            name='ix_maint_pmsched_act_due',
        ),
        migrations.RemoveIndex(
            model_name='pmtask',
            name='ix_maint_pmtask_num',
        ),
        migrations.RemoveIndex(
            model_name='pmtask',
            name='ix_maint_pmtask_stat_prio',
        ),
        migrations.RemoveIndex(
            model_name='pmtask',
            name='ix_maint_pmtask_assigned',
        ),
        migrations.RemoveIndex(
            model_name='productionimpact',
            name='ix_maint_pi_dt_event',
        ),
        migrations.RemoveIndex(
            model_name='productionimpact',
            name='ix_maint_pi_batch',
        ),
        migrations.RemoveIndex(
            model_name='productionimpact',
            name='ix_maint_pi_job',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='maintenance_asset_c_23b943_idx',
            old_name='ix_maint_asset_code',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='maintenance_status_896760_idx',
            old_name='ix_maint_asset_stat_crit',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='maintenance_qr_toke_4f4b3b_idx',
            old_name='ix_maint_asset_qr',
        ),
        migrations.RenameIndex(
            model_name='downtimeevent',
            new_name='maintenance_asset_i_d12052_idx',
            old_name='ix_maint_dt_asset_start',
        ),
        migrations.RenameIndex(
            model_name='pmtask',
            new_name='maintenance_status_8c9000_idx',
            old_name='ix_maint_pmtask_stat_sched',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='current_meter_reading',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='depreciation_rate',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='is_critical_production_asset',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last_maintenance_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last_meter_update',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='next_pm_due_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='parent_asset',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='warranty_expiry_date',
        ),
        migrations.RemoveField(
            model_name='assetcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='assetcategory',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='assetcategory',
            name='requires_certification',
        ),
        migrations.RemoveField(
            model_name='assetcategory',
            name='sort_order',
        ),
        migrations.AlterUniqueTogether(
            name='assetdocument',
            unique_together={('asset', 'document')},
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='building',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='floor_level',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='responsible_person_id',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='responsible_person_name',
        ),
        migrations.RemoveField(
            model_name='assetlocation',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='downtimeevent',
            name='downtime_type',
        ),
        migrations.RemoveField(
            model_name='downtimeevent',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='downtimeevent',
            name='production_affected',
        ),
        migrations.RemoveField(
            model_name='downtimeevent',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='downtimeevent',
            name='reason_detail',
        ),
        migrations.RemoveField(
            model_name='downtimeevent',
            name='severity_score',
        ),
        migrations.RemoveField(
            model_name='downtimeevent',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='downtimeevent',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='actual_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='completion_notes',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='follow_up_notes',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='follow_up_required',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='issues_found',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='meter_reading_at_completion',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='performed_by_id',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='performed_by_name',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='pmtask',
            name='task_number',
        ),
        migrations.RemoveField(
            model_name='productionimpact',
            name='actual_completion',
        ),
        migrations.RemoveField(
            model_name='productionimpact',
            name='batch_order_id',
        ),
        migrations.RemoveField(
            model_name='productionimpact',
            name='batch_order_number',
        ),
        migrations.RemoveField(
            model_name='productionimpact',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='productionimpact',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='productionimpact',
            name='planned_completion',
        ),
        migrations.RemoveField(
            model_name='productionimpact',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='productionimpact',
            name='rework_required',
        ),
        migrations.RemoveField(
            model_name='productionimpact',
            name='scrap_generated',
        ),
        migrations.RemoveField(
            model_name='productionimpact',
            name='units_affected',
        ),
        migrations.AddField(
            model_name='asset',
            name='barcode',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='expected_life_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='has_safety_lockout',
            field=models.BooleanField(default=False, help_text='Requires LOTO procedures'),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Critical asset that can stop production'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_pm_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='meter_reading',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current meter/hour reading', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='next_pm_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='primary_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_assets', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='asset',
            name='requires_certification',
            field=models.BooleanField(default=False, help_text='Operators need certification'),
        ),
        migrations.AddField(
            model_name='asset',
            name='responsible_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='hr.department'),
        ),
        migrations.AddField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='year_manufactured',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='color',
            field=models.CharField(default='#6366f1', max_length=7),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='default_criticality',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_usages', to='knowledge.document'),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='document_type',
            field=models.CharField(choices=[('MANUAL', 'User Manual'), ('OEM_GUIDE', 'OEM Guide'), ('SOP', 'Standard Operating Procedure'), ('DRAWING', 'Technical Drawing'), ('WARRANTY', 'Warranty Document'), ('CERTIFICATE', 'Calibration/Certificate'), ('SAFETY', 'Safety Data Sheet'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='assetdocument',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary document for this type'),
        ),
        migrations.AddField(
            model_name='assetlocation',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='downtimeevent',
            name='event_type',
            field=models.CharField(choices=[('UNPLANNED_BREAKDOWN', 'Unplanned Breakdown'), ('PLANNED_PM', 'Planned PM'), ('SETUP_CHANGEOVER', 'Setup/Changeover'), ('WAITING_PARTS', 'Waiting for Parts'), ('UTILITY_FAILURE', 'Utility Failure (Power/Air)'), ('OPERATOR_ABSENCE', 'Operator Absence'), ('QUALITY_ISSUE', 'Quality Hold'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='downtimeevent',
            name='has_production_impact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downtimeevent',
            name='is_planned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downtimeevent',
            name='reason_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='downtimeevent',
            name='severity',
            field=models.CharField(choices=[('MINOR', 'Minor (< 1 hour)'), ('MODERATE', 'Moderate (1-4 hours)'), ('MAJOR', 'Major (4-8 hours)'), ('CRITICAL', 'Critical (> 8 hours)')], default='MODERATE', max_length=10),
        ),
        migrations.AddField(
            model_name='pmschedule',
            name='auto_generated',
            field=models.BooleanField(default=True, help_text='System-generated vs manual'),
        ),
        migrations.AddField(
            model_name='pmschedule',
            name='custom_frequency_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmschedule',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pmschedule',
            name='last_performed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmschedule',
            name='meter_reading_at_last_pm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pmtask',
            name='corrective_action_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pmtask',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmtask',
            name='findings',
            field=models.TextField(blank=True, help_text='Issues discovered during PM'),
        ),
        migrations.AddField(
            model_name='pmtask',
            name='meter_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pmtask',
            name='next_due_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pmtask',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pmtask',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_tasks_performed', to='hr.hremployee'),
        ),
        migrations.AddField(
            model_name='pmtask',
            name='work_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_pm_task', to='maintenance.workorder'),
        ),
        migrations.AddField(
            model_name='productionimpact',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionimpact',
            name='batch_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='FK to Batch when available', null=True),
        ),
        migrations.AddField(
            model_name='productionimpact',
            name='batch_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productionimpact',
            name='currency',
            field=models.CharField(default='SAR', max_length=3),
        ),
        migrations.AddField(
            model_name='productionimpact',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productionimpact',
            name='expected_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionimpact',
            name='impact_type',
            field=models.CharField(choices=[('BATCH', 'Batch/Order'), ('JOB_CARD', 'Individual Job Card'), ('OPERATION', 'Specific Operation')], default='BATCH', max_length=20),
        ),
        migrations.AddField(
            model_name='productionimpact',
            name='is_revenue_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionimpact',
            name='lost_or_delayed_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionimpact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productionimpact',
            name='operation_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='FK to Operation when available', null=True),
        ),
        migrations.AddField(
            model_name='productionimpact',
            name='product_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(help_text='Internal asset tag (e.g., GRN-001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='maintenance.assetcategory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='criticality',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical - Production Stopper')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='erp_asset_number',
            field=models.CharField(blank=True, help_text='ERP system asset ID', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='maintenance.assetlocation'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='meter_unit',
            field=models.CharField(default='hours', help_text='e.g., hours, cycles, km', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='qr_token',
            field=models.CharField(blank=True, help_text='Unique token for QR code scanning', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='replacement_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Technical specifications'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('IN_SERVICE', 'In Service'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service'), ('STANDBY', 'Standby'), ('SCRAPPED', 'Scrapped')], default='IN_SERVICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='code',
            field=models.CharField(help_text='Short code like GRN, OVN', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='default_pm_interval_days',
            field=models.PositiveIntegerField(blank=True, help_text='Default PM frequency in days', null=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='assetdocument',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='maintenance.asset'),
        ),
        migrations.AlterField(
            model_name='assetdocument',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assetlocation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='maintenance.assetlocation'),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='downtime_events', to='maintenance.asset'),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical'), ('HYDRAULIC', 'Hydraulic'), ('PNEUMATIC', 'Pneumatic'), ('CONTROL_SOFTWARE', 'Control/Software'), ('WEAR', 'Wear & Tear'), ('MISUSE', 'Operator Error'), ('UTILITY', 'Utility Issue'), ('MATERIAL', 'Material Issue'), ('TOOLING', 'Tooling Issue'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='downtimeevent',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_events', to='maintenance.workorder'),
        ),
        migrations.AlterField(
            model_name='pmschedule',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_schedules', to='maintenance.asset'),
        ),
        migrations.AlterField(
            model_name='pmschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pmschedule',
            name='next_due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pmschedule',
            name='next_due_meter_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pmtask',
            name='actual_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pmtask',
            name='actual_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pmtask',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='maintenance.pmschedule'),
        ),
        migrations.AlterField(
            model_name='pmtask',
            name='scheduled_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pmtask',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionimpact',
            name='delay_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionimpact',
            name='downtime_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_impacts', to='maintenance.downtimeevent'),
        ),
        migrations.AlterField(
            model_name='productionimpact',
            name='impact_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productionimpact',
            name='job_card_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='FK to JobCard when available', null=True),
        ),
        migrations.AlterField(
            model_name='productionimpact',
            name='job_card_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['category', 'status'], name='maintenance_categor_b2d794_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['location', 'status'], name='maintenance_locatio_e64be4_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_critical'], name='maintenance_is_crit_bcf055_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['-last_pm_date'], name='idx_asset_last_maint'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['next_pm_date'], name='idx_asset_next_pm'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['manufacturer', 'model_number'], name='idx_asset_mfr_model'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_deleted', 'status'], name='idx_asset_active'),
        ),
        migrations.AddIndex(
            model_name='downtimeevent',
            index=models.Index(fields=['event_type', 'start_time'], name='maintenance_event_t_e2a4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='downtimeevent',
            index=models.Index(fields=['is_planned'], name='maintenance_is_plan_defaec_idx'),
        ),
        migrations.AddIndex(
            model_name='downtimeevent',
            index=models.Index(fields=['has_production_impact'], name='maintenance_has_pro_475256_idx'),
        ),
        migrations.AddIndex(
            model_name='pmtask',
            index=models.Index(fields=['schedule', 'scheduled_date'], name='maintenance_schedul_ffc526_idx'),
        ),
        migrations.AlterModelTable(
            name='asset',
            table=None,
        ),
        migrations.AlterModelTable(
            name='assetcategory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='assetdocument',
            table=None,
        ),
        migrations.AlterModelTable(
            name='assetlocation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='downtimeevent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pmschedule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pmtask',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productionimpact',
            table=None,
        ),
        migrations.AddField(
            model_name='assetmeterreading',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='maintenance.asset'),
        ),
        migrations.AddField(
            model_name='assetmeterreading',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostsalesrecord',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostsalesrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostsalesrecord',
            name='production_impact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lost_sales_record', to='maintenance.productionimpact'),
        ),
        migrations.AddField(
            model_name='lostsalesrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmtemplate',
            name='applies_to_assets',
            field=models.ManyToManyField(blank=True, help_text='Specific assets (overrides category)', related_name='assigned_pm_templates', to='maintenance.asset'),
        ),
        migrations.AddField(
            model_name='pmtemplate',
            name='applies_to_category',
            field=models.ForeignKey(blank=True, help_text='Apply to all assets of this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_templates', to='maintenance.assetcategory'),
        ),
        migrations.AddField(
            model_name='pmtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmtemplate',
            name='linked_procedure',
            field=models.ForeignKey(blank=True, help_text='Linked SOP/procedure from Knowledge module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_templates', to='knowledge.article'),
        ),
        migrations.AddField(
            model_name='pmtemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pmschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pmschedule',
            name='pm_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='maintenance.pmtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='pmschedule',
            unique_together={('asset', 'pm_template')},
        ),
        migrations.AddIndex(
            model_name='pmschedule',
            index=models.Index(fields=['next_due_date', 'is_active'], name='maintenance_next_du_946c66_idx'),
        ),
        migrations.AddIndex(
            model_name='pmschedule',
            index=models.Index(fields=['is_overdue', 'is_active'], name='maintenance_is_over_47956f_idx'),
        ),
        migrations.AddField(
            model_name='workordernote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workordernote',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='maintenance.workorder'),
        ),
        migrations.AddField(
            model_name='workorderpart',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_parts', to='maintenance.workorder'),
        ),
        migrations.DeleteModel(
            name='LostSales',
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='is_current_version',
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='title',
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='assetdocument',
            name='version',
        ),
        migrations.AddIndex(
            model_name='assetmeterreading',
            index=models.Index(fields=['asset', 'reading_date'], name='maintenance_asset_i_ea7e47_idx'),
        ),
        migrations.RemoveField(
            model_name='pmschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pmschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pmschedule',
            name='custom_interval_days',
        ),
        migrations.RemoveField(
            model_name='pmschedule',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='pmschedule',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='pmschedule',
            name='last_completed_date',
        ),
        migrations.RemoveField(
            model_name='pmschedule',
            name='last_meter_reading_at_pm',
        ),
        migrations.RemoveField(
            model_name='pmschedule',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='pmschedule',
            name='pm_plan',
        ),
        migrations.RemoveField(
            model_name='pmschedule',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='pmschedule',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='pmschedule',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pmschedule',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='PMPlan',
        ),
    ]
