# Generated by Django 5.2.6 on 2025-10-17 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_app', '0002_alter_account_created_by_alter_account_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_id', help_text='Login account for this employee (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
