# Generated by Django 5.2.6 on 2025-10-24 18:10

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_app', '0002_create_hrphone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hrphone',
            name='uq_hr_phone_number_ext',
        ),
        migrations.AddField(
            model_name='hrphone',
            name='calling_code',
            field=models.CharField(blank=True, default='', max_length=5, validators=[django.core.validators.RegexValidator('^\\+\\d{1,3}$', 'Use a valid country calling code like +966, +1, +44')]),
        ),
        migrations.AddField(
            model_name='hrphone',
            name='country_iso2',
            field=models.CharField(blank=True, default='', help_text='ISO-3166 alpha-2 (e.g., SA, US)', max_length=2),
        ),
        migrations.AddField(
            model_name='hrphone',
            name='national_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\d{4,15}$', 'Digits only, 4–15 long')]),
        ),
        migrations.AlterField(
            model_name='hrphone',
            name='channel',
            field=models.CharField(choices=[('CALL', 'Call'), ('WHATS', 'Whats')], default='CALL', max_length=8),
        ),
        migrations.AlterField(
            model_name='hrphone',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='hrphone',
            name='phone_e164',
            field=models.CharField(db_index=True, editable=False, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='hrphone',
            constraint=models.UniqueConstraint(fields=('phone_e164', 'extension'), name='uq_hr_phone_e164_ext'),
        ),
    ]
