# Generated by Django 5.2.6 on 2025-10-24 18:10

from django.db import migrations

def backfill_natnum(apps, schema_editor):
    import phonenumbers
    HRPhone = apps.get_model('floor_app', 'HRPhone')
    for p in HRPhone.objects.all():
        if p.phone_e164 and not p.national_number:
            try:
                pn = phonenumbers.parse(p.phone_e164, None)
                p.calling_code = f"+{pn.country_code}" if not p.calling_code else p.calling_code
                if not p.country_iso2 and pn.country_code:
                    # country_iso2 optional; keep as-is if unknown
                    pass
                p.national_number = str(pn.national_number)
                p.save(update_fields=['calling_code','national_number'])
            except Exception:
                # leave as is; you can fix manually in admin if parsing fails
                pass

class Migration(migrations.Migration):
    dependencies = [
        ('floor_app', '0003_hrphone_add_nullable_national_number'),  # <-- use the actual number you see
    ]

    operations = [migrations.RunPython(backfill_natnum, migrations.RunPython.noop)]

