# Generated by Django 5.2.6 on 2025-10-17 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('floor_app', '0003_alter_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='auth_group',
            field=models.ForeignKey(blank=True, help_text='Permissions group for this employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='auth.group'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, db_column='user_id', help_text='Login account for this employee (auto-created if empty).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_record', to=settings.AUTH_USER_MODEL),
        ),
    ]
