# Generated by Django 5.2.6 on 2025-10-19 16:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('floor_app', '0004_employee_auth_group_employee_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('method_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('e164_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{6,14}$', 'Use E.164 format, e.g., +966512345678')])),
                ('is_whatsapp', models.BooleanField(default=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contact_methods',
                'ordering': ['contact_id', 'kind', '-is_primary', '-is_whatsapp', 'label'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['party_type', 'party_id', '-is_primary', 'kind', 'last_name', 'first_name', 'company_name']},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='designation',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='primary_contact',
            field=models.ForeignKey(blank=True, db_column='primary_contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses_as_primary', to='floor_app.contact'),
        ),
        migrations.AddField(
            model_name='address',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carrier',
            name='primary_contact',
            field=models.ForeignKey(blank=True, db_column='primary_contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carriers_as_primary', to='floor_app.contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_contact',
            field=models.ForeignKey(blank=True, db_column='primary_contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_as_primary', to='floor_app.contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='kind',
            field=models.CharField(choices=[('person', 'Person'), ('company', 'Company')], db_index=True, default='person', max_length=16),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_contact',
            field=models.ForeignKey(blank=True, db_column='primary_contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_as_primary', to='floor_app.contact'),
        ),
        migrations.AddField(
            model_name='employee',
            name='allow_admin_login',
            field=models.BooleanField(db_index=True, default=False, help_text='If checked, the linked user can sign in to Django admin (sets is_staff).'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='primary_contact',
            field=models.ForeignKey(blank=True, db_column='primary_contact_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_as_primary', to='floor_app.contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='party_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='party_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['party_type', 'party_id', 'is_primary'], name='ix_contact_party_primary'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['kind', 'last_name', 'first_name'], name='ix_contact_person_name'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['kind', 'company_name'], name='ix_contact_company_name'),
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='floor_app.contact'),
        ),
        migrations.AddIndex(
            model_name='contactmethod',
            index=models.Index(fields=['contact', 'kind'], name='contact_met_contact_b55bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmethod',
            index=models.Index(fields=['kind'], name='contact_met_kind_63ae89_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('contact', 'kind'), name='uq_contactmethod_primary_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.UniqueConstraint(fields=('contact', 'kind', 'e164_phone', 'email'), name='uq_contactmethod_unique_value'),
        ),
    ]
