# Generated by Django 5.2.6 on 2025-10-21 01:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('floor_app', '0005_contactmethod_alter_contact_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('link_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner_object_id', models.BigIntegerField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('type', models.CharField(choices=[('home', 'Home'), ('office', 'Office/HQ'), ('warehouse', 'Warehouse/Site'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'addresses_link',
                'ordering': ['owner_content_type', 'owner_object_id', 'type', 'sequence'],
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['country_code', 'region', 'city', 'neighborhood', 'street_name', 'building_no']},
        ),
        migrations.RemoveConstraint(
            model_name='address',
            name='uq_address_primary_per_party',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='address',
            name='party_id',
        ),
        migrations.RemoveField(
            model_name='address',
            name='party_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.RemoveField(
            model_name='address',
            name='title',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='party_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='party_type',
        ),
        migrations.AddField(
            model_name='address',
            name='additional_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='building_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='country_code',
            field=models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 (e.g., 'SA' for Saudi Arabia).", max_length=2, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Must be ISO 3166-1 alpha-2 (e.g., SA, JO, US).')]),
        ),
        migrations.AddField(
            model_name='address',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='address',
            name='normalized_text',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='address',
            name='po_box',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='address',
            name='street_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='address',
            name='unit_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='party_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_party_ct', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='party_object_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, help_text='KSA: 5 digits (e.g., 12345). Other formats accepted.', max_length=12),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country_code', 'region', 'city'], name='ix_addr_cc_region_city'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['neighborhood'], name='ix_addr_neighborhood'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['postal_code'], name='ix_addr_postal'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['fingerprint'], name='ix_addr_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('country_code', 'region', 'city', 'neighborhood', 'street_name', 'building_no', 'additional_no', 'unit_no', 'postal_code', 'line1', 'line2', 'po_box'), name='uq_addr_exact_tuple'),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='floor_app.address'),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='owner_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_links', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='addresslink',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='addresslink',
            index=models.Index(fields=['owner_content_type', 'owner_object_id', 'type'], name='ix_addr_owner_type'),
        ),
        migrations.AddConstraint(
            model_name='addresslink',
            constraint=models.UniqueConstraint(fields=('owner_content_type', 'owner_object_id', 'address'), name='uq_addr_link_owner_address'),
        ),
        migrations.AddConstraint(
            model_name='addresslink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('owner_content_type', 'owner_object_id', 'type'), name='uq_addr_primary_per_owner_type'),
        ),
    ]
