# Generated by Django 5.2.6 on 2025-10-25 15:05

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_app', '0005_alter_hrphone_calling_code_alter_hrphone_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HREmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('kind', models.CharField(choices=[('PERSONAL', 'Personal'), ('BUSINESS', 'Business')], default='BUSINESS', max_length=8)),
                ('is_primary_hint', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, default='', max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_hr_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_hr_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_email',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uq_hr_email_ci')],
            },
        ),
    ]
