# Generated by Django 5.2.6 on 2025-10-25 16:14

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_app', '0007_create_hraddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hraddress',
            name='uq_hr_address_ci_tuple',
        ),
        migrations.AddField(
            model_name='hraddress',
            name='additional_number',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='hraddress',
            name='address_kind',
            field=models.CharField(choices=[('STREET', 'Street address'), ('PO_BOX', 'PO Box')], default='STREET', max_length=8),
        ),
        migrations.AddField(
            model_name='hraddress',
            name='building_number',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='hraddress',
            name='components',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hraddress',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='hraddress',
            name='po_box',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hraddress',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hraddress',
            name='unit_number',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='hraddress',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('country_iso2'), django.db.models.functions.text.Lower('city'), django.db.models.functions.text.Lower('neighborhood'), django.db.models.functions.text.Lower('street_name'), django.db.models.functions.text.Lower('building_number'), django.db.models.functions.text.Lower('unit_number'), condition=models.Q(('address_kind', 'STREET')), name='uq_hr_address_street_tuple_ci'),
        ),
        migrations.AddConstraint(
            model_name='hraddress',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('country_iso2'), django.db.models.functions.text.Lower('city'), django.db.models.functions.text.Lower('po_box'), condition=models.Q(('address_kind', 'PO_BOX')), name='uq_hr_address_pobox_tuple_ci'),
        ),
    ]
