# Generated by Django 5.2.6 on 2025-10-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floor_app', '0010_update_hrpeople_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrpeople',
            name='national_id_expiry',
        ),
    ]
