# Generated by Django 5.2.6 on 2025-11-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_app', '0011_drop_national_id_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='hraddress',
            name='public_id',
            field=models.UUIDField(
                null=True,
                blank=True,
                editable=False,
                db_index=True,
            ),
        ),

        migrations.AddField(
            model_name='hrpeople',
            name='public_id',
            field=models.UUIDField(
                null=True,
                blank=True,
                editable=False,
                db_index=True,
            ),
        ),

    ]
