# Generated by Django 5.2.6 on 2025-11-07 11:35

from django.db import migrations
import uuid


def populate_public_ids(apps, schema_editor):
    # Use historical versions of the models
    HRPeople = apps.get_model('floor_app', 'HRPeople')
    HRAddress = apps.get_model('floor_app', 'HRAddress')

    for Model in (HRPeople, HRAddress):
        for obj in Model.objects.filter(public_id__isnull=True):
            obj.public_id = uuid.uuid4()
            obj.save(update_fields=['public_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('floor_app', '0012_hraddress_public_id_hrpeople_public_id'),
    ]

    operations = [
        migrations.RunPython(populate_public_ids, migrations.RunPython.noop),
    ]

