# Generated by Django 5.2.6 on 2025-11-07 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_app', '0013_populate_public_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hraddress',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hrpeople',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
