# Generated by Django 5.2.6 on 2025-11-08 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_app', '0014_alter_hraddress_public_id_alter_hrpeople_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hraddress',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='floor_app.hrpeople'),
        ),
        migrations.AddField(
            model_name='hremail',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='floor_app.hrpeople'),
        ),
        migrations.AddField(
            model_name='hrphone',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='floor_app.hrpeople'),
        ),
        migrations.CreateModel(
            name='HREmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('employee_no', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On leave'), ('SUSPENDED', 'Suspended'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=16)),
                ('job_title', models.CharField(blank=True, default='', max_length=120)),
                ('team', models.CharField(blank=True, default='', max_length=64)),
                ('is_operator', models.BooleanField(default=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_hr_created', to=settings.AUTH_USER_MODEL)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='floor_app.hrpeople')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_hr_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_employee',
                'ordering': ['employee_no'],
            },
        ),
        migrations.CreateModel(
            name='HRQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('issuer_type', models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=16)),
                ('validity_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requires_renewal', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_hr_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_hr_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_qualification',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HREmployeeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('PENDING', 'Pending')], default='ACTIVE', max_length=16)),
                ('doc_ref', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_hr_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='floor_app.hremployee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_hr_updated', to=settings.AUTH_USER_MODEL)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_links', to='floor_app.hrqualification')),
            ],
            options={
                'db_table': 'hr_employee_qualification',
                'indexes': [models.Index(fields=['employee', 'qualification', 'status'], name='hr_employee_employe_a1d1a3_idx')],
            },
        ),
    ]
