# Generated by Django 5.2.6 on 2025-11-23 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "floor_app",
            "0029_helpcategory_apikey_dashboardlayout_dashboardwidget_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserThemePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light Mode"),
                            ("dark", "Dark Mode"),
                            ("auto", "Auto (System)"),
                            ("custom", "Custom Colors"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                (
                    "high_contrast",
                    models.BooleanField(
                        default=False,
                        help_text="Enable high contrast mode for accessibility",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#2563eb", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#10b981", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("small", "Small (14px)"),
                            ("medium", "Medium (16px)"),
                            ("large", "Large (18px)"),
                            ("x-large", "Extra Large (20px)"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        default="system",
                        help_text="Font family preference",
                        max_length=100,
                    ),
                ),
                (
                    "line_height",
                    models.DecimalField(
                        decimal_places=1,
                        default=1.5,
                        help_text="Line height multiplier",
                        max_digits=3,
                    ),
                ),
                ("sidebar_collapsed", models.BooleanField(default=False)),
                (
                    "density",
                    models.CharField(
                        choices=[
                            ("compact", "Compact"),
                            ("comfortable", "Comfortable"),
                            ("spacious", "Spacious"),
                        ],
                        default="comfortable",
                        max_length=20,
                    ),
                ),
                (
                    "show_animations",
                    models.BooleanField(default=True, help_text="Enable UI animations"),
                ),
                (
                    "reduce_motion",
                    models.BooleanField(
                        default=False, help_text="Reduce motion for accessibility"
                    ),
                ),
                (
                    "focus_indicators",
                    models.BooleanField(
                        default=True, help_text="Show enhanced focus indicators"
                    ),
                ),
                ("screen_reader_optimized", models.BooleanField(default=False)),
                (
                    "mobile_view",
                    models.CharField(
                        choices=[
                            ("auto", "Auto Detect"),
                            ("mobile", "Always Mobile"),
                            ("desktop", "Always Desktop"),
                        ],
                        default="auto",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Theme Preference",
                "verbose_name_plural": "User Theme Preferences",
            },
        ),
    ]
