# Generated by Django 5.2.6 on 2025-11-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("floor_app", "0030_userthemepreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userthemepreference",
            name="background_color",
            field=models.CharField(
                default="#ffffff", help_text="Main background color (hex)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="userthemepreference",
            name="text_color",
            field=models.CharField(
                default="#1f2937", help_text="Primary text color (hex)", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="userthemepreference",
            name="accent_color",
            field=models.CharField(
                default="#10b981",
                help_text="Accent/highlight color (hex)",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="userthemepreference",
            name="primary_color",
            field=models.CharField(
                default="#2563eb", help_text="Primary brand color (hex)", max_length=7
            ),
        ),
    ]
