# Generated by Django 5.2.6 on 2025-11-23 04:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("email_for_errors", models.BooleanField(default=True)),
                ("email_for_warnings", models.BooleanField(default=True)),
                ("email_for_info", models.BooleanField(default=False)),
                ("email_for_tasks", models.BooleanField(default=True)),
                ("daily_digest", models.BooleanField(default=False)),
                ("digest_time", models.TimeField(default="09:00:00")),
                ("play_sound", models.BooleanField(default=True)),
                ("desktop_notifications", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="UserThemePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light Mode"),
                            ("dark", "Dark Mode"),
                            ("auto", "Auto (System Preference)"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                (
                    "color_scheme",
                    models.CharField(
                        choices=[
                            ("blue", "Blue (Default)"),
                            ("green", "Green"),
                            ("purple", "Purple"),
                            ("orange", "Orange"),
                            ("red", "Red"),
                            ("teal", "Teal"),
                        ],
                        default="blue",
                        max_length=20,
                    ),
                ),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium (Default)"),
                            ("large", "Large"),
                            ("xlarge", "Extra Large"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "high_contrast",
                    models.BooleanField(
                        default=False,
                        help_text="Enable high contrast mode for better readability",
                    ),
                ),
                (
                    "reduce_motion",
                    models.BooleanField(
                        default=False, help_text="Reduce animations and transitions"
                    ),
                ),
                ("sidebar_collapsed", models.BooleanField(default=False)),
                (
                    "compact_mode",
                    models.BooleanField(
                        default=False, help_text="Use compact spacing for more content"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme Preference",
                "verbose_name_plural": "Theme Preferences",
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("PAGE_VIEW", "Page View"),
                            ("SEARCH", "Search"),
                            ("FILTER", "Filter"),
                            ("DOWNLOAD", "Download"),
                            ("UPLOAD", "Upload"),
                            ("API_CALL", "API Call"),
                            ("REPORT", "Report Generation"),
                            ("PRINT", "Print"),
                        ],
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(blank=True, max_length=500)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("description", models.TextField(blank=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration of the activity in milliseconds",
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="floor_core__user_id_a3cac9_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "-timestamp"],
                        name="floor_core__activit_284e54_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="floor_core__timesta_9e24e2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150)),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("object_repr", models.CharField(blank=True, max_length=200)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("VIEW", "View"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("APPROVE", "Approve"),
                            ("REJECT", "Reject"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_name", models.CharField(blank=True, max_length=100)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("message", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="floor_core__user_id_e7495e_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id", "-timestamp"],
                        name="floor_core__content_d15649_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="floor_core__action_b9ca40_idx",
                    ),
                    models.Index(
                        fields=["-timestamp"], name="floor_core__timesta_3a93f0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChangeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                (
                    "field_changes",
                    models.JSONField(
                        help_text="JSON object with field: {old, new} pairs"
                    ),
                ),
                ("change_summary", models.TextField(blank=True)),
                (
                    "changed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("change_reason", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Change History",
                "verbose_name_plural": "Change Histories",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-changed_at"],
                        name="floor_core__content_e1fd82_idx",
                    ),
                    models.Index(
                        fields=["changed_by", "-changed_at"],
                        name="floor_core__changed_dd4701_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("TASK", "Task"),
                            ("REMINDER", "Reminder"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("action_text", models.CharField(blank=True, max_length=100)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="floor_core__user_id_cf5976_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="floor_core__user_id_8f8f54_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System"),
                            ("SECURITY", "Security"),
                            ("DATABASE", "Database"),
                            ("EMAIL", "Email"),
                            ("API", "API"),
                            ("TASK", "Background Task"),
                            ("INTEGRATION", "Integration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_name", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("exception_type", models.CharField(blank=True, max_length=200)),
                ("exception_message", models.TextField(blank=True)),
                ("stack_trace", models.TextField(blank=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("request_path", models.CharField(blank=True, max_length=500)),
                ("request_method", models.CharField(blank=True, max_length=10)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Event",
                "verbose_name_plural": "System Events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["level", "-timestamp"],
                        name="floor_core__level_60be7c_idx",
                    ),
                    models.Index(
                        fields=["category", "-timestamp"],
                        name="floor_core__categor_6a540c_idx",
                    ),
                    models.Index(
                        fields=["is_resolved", "-timestamp"],
                        name="floor_core__is_reso_a949cd_idx",
                    ),
                ],
            },
        ),
    ]
