# Generated by Django 5.2.6 on 2025-11-18 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_users", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("new_users", models.IntegerField(default=0)),
                ("total_logins", models.IntegerField(default=0)),
                ("total_page_views", models.IntegerField(default=0)),
                ("total_actions", models.IntegerField(default=0)),
                (
                    "avg_session_duration_seconds",
                    models.FloatField(blank=True, null=True),
                ),
                ("avg_page_load_time_ms", models.FloatField(blank=True, null=True)),
                ("total_errors", models.IntegerField(default=0)),
                ("critical_errors", models.IntegerField(default=0)),
                ("module_statistics", models.JSONField(blank=True, default=dict)),
                ("peak_concurrent_users", models.IntegerField(default=0)),
                ("peak_hour", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Daily Statistics",
                "db_table": "analytics_daily_statistics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ModuleUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(db_index=True, max_length=50)),
                ("date", models.DateField(db_index=True)),
                ("page_views", models.IntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
                ("total_actions", models.IntegerField(default=0)),
                ("creates", models.IntegerField(default=0)),
                ("reads", models.IntegerField(default=0)),
                ("updates", models.IntegerField(default=0)),
                ("deletes", models.IntegerField(default=0)),
                ("avg_load_time_ms", models.FloatField(blank=True, null=True)),
                ("total_time_seconds", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analytics_module_usage",
                "ordering": ["-date", "module"],
                "indexes": [
                    models.Index(
                        fields=["module", "-date"], name="analytics_m_module_f46f3d_idx"
                    )
                ],
                "unique_together": {("module", "date")},
            },
        ),
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("response_time", "Response Time"),
                            ("error_rate", "Error Rate"),
                            ("cpu_usage", "CPU Usage"),
                            ("memory_usage", "Memory Usage"),
                            ("disk_usage", "Disk Usage"),
                            ("database_queries", "Database Queries"),
                            ("active_users", "Active Users"),
                            ("concurrent_sessions", "Concurrent Sessions"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("value", models.FloatField()),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "analytics_system_metric",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "-timestamp"],
                        name="analytics_s_metric__1c01a2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("device_type", models.CharField(blank=True, max_length=50)),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("operating_system", models.CharField(blank=True, max_length=50)),
                ("login_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_activity", models.DateTimeField(auto_now=True, db_index=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_user_session",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("search", "Search"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("submit", "Submit"),
                            ("download", "Download"),
                            ("upload", "Upload"),
                            ("print", "Print"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("module", models.CharField(blank=True, db_index=True, max_length=50)),
                ("description", models.CharField(max_length=500)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="analytics.usersession",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Activities",
                "db_table": "analytics_user_activity",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(blank=True, db_index=True, max_length=50)),
                ("search_term", models.CharField(db_index=True, max_length=500)),
                ("filters_applied", models.JSONField(blank=True, default=dict)),
                ("results_count", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("clicked_result", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches",
                        to="analytics.usersession",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Search Queries",
                "db_table": "analytics_search_query",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(db_index=True, max_length=500)),
                (
                    "url_name",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("module", models.CharField(blank=True, db_index=True, max_length=50)),
                ("view_name", models.CharField(blank=True, max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("referrer", models.CharField(blank=True, max_length=500)),
                (
                    "load_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Page load time in milliseconds",
                        null=True,
                    ),
                ),
                ("query_params", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to="analytics.usersession",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_page_view",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="error",
                        max_length=20,
                    ),
                ),
                ("error_type", models.CharField(db_index=True, max_length=100)),
                ("error_message", models.TextField()),
                ("url", models.CharField(blank=True, max_length=500)),
                ("module", models.CharField(blank=True, db_index=True, max_length=50)),
                ("view_name", models.CharField(blank=True, max_length=100)),
                ("traceback", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_errors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="error_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="errors",
                        to="analytics.usersession",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_error_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "-login_time"], name="analytics_u_user_id_fa0d9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["is_active", "-last_activity"],
                name="analytics_u_is_acti_736e92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "-timestamp"], name="analytics_u_user_id_ffdb9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["action_type", "-timestamp"],
                name="analytics_u_action__85767e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["module", "-timestamp"], name="analytics_u_module_dbb5a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="analytics_u_content_32e233_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["module", "-timestamp"], name="analytics_s_module_0e5d32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["search_term"], name="analytics_s_search__62498e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["user", "-timestamp"], name="analytics_p_user_id_47842f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["module", "-timestamp"], name="analytics_p_module_bb7973_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["url_name", "-timestamp"], name="analytics_p_url_nam_135a28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["severity", "-timestamp"], name="analytics_e_severit_a740d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["module", "-timestamp"], name="analytics_e_module_1fd477_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errorlog",
            index=models.Index(
                fields=["is_resolved", "-timestamp"],
                name="analytics_e_is_reso_a88831_idx",
            ),
        ),
    ]
